### PR TITLE
Feat/add btp UI

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by hetfly** [comment]
Add this to .env to work locally
```
REACT_APP_VERSION=$npm_package_version
REACT_APP_BTP_ENDPOINT_MOONBEAM=http://3.15.169.101:8000/v1
REACT_APP_BTP_ENDPOINT_BSC=http://18.141.139.244:8000/v1

# NEAR
REACT_APP_NEAR_NODE_URL=https://rpc.testnet.near.org
REACT_APP_NEAR_WALLET_URL=https://wallet.testnet.near.org
REACT_APP_NEAR_HELPER_URL=https://helper.testnet.near.org
REACT_APP_NEAR_EXPLORER_URL=https://explorer.testnet.near.org
REACT_APP_NEAR_CONTRACT_ID=guest-book.testnet
REACT_APP_NEAR_NETWORK_ID=testnet

# BSC
REACT_APP_BSC_RPC_URL=http://18.141.139.244:8545
REACT_APP_BSC_NETWORK_ADDRESS=0x97.bsc
REACT_APP_BSC_BSH_CORE=0x8c2e5FC5d651129Ce7296847DcFaC62c646E4E3D
REACT_APP_BSC_TOKEN_BSH_PROXY=0x71a1520bBb7e6072Bbf3682A60c73D63b693690A
REACT_APP_BSC_BEP20_TKN=0xBA34F3c6893b12fF4115ACf1b4712C6E2783aD83

# Moonbeam
REACT_APP_MB_RPC_URL=https://moonbeam-alpha.api.onfinality.io/public
REACT_APP_MB_BSH_CORE=0x910d65A483075CAfdFe5d3302909a42443DC5013
REACT_APP_MB_BSH_ICX=0x7b329aA204fe2c790f714C5A25123bb2DaC86632
REACT_APP_MB_NETWORK_ADDRESS=0x507.pra
REACT_APP_MB_GAS_LIMIT=6691B7

# ICON-MOONBEAM \
# https://icondev.io/introduction/the-icon-network/testnet#berlin
REACT_APP_ICON_RPC_URL=https://berlin.net.solidwallet.io/api/v3
REACT_APP_ICON_NID=0x7
REACT_APP_ICON_NETWORK_ADDRESS=0x7.icon
REACT_APP_ICON_IRC2_TOKEN=cx824f3b2f2a8f59ac3d281b1b9bc295e051be5274
REACT_APP_ICON_BSH_ADDRESS=cxfbb263e84f261b2686e5b28acd7f9951fb34998c
REACT_APP_ICON_STEP_LIMIT=3519157719

# ICON-BSC
REACT_APP_ICON_BSC_RPC_URL=http://18.141.139.244:9080/api/v3/icon
REACT_APP_ICON_BSC_NID=0xbe04ab
REACT_APP_ICON_BSC_NETWORK_ADDRESS=0xbe04ab.icon
REACT_APP_ICON_BSC_BSH_ADDRESS=cxd1ecd352d80797ac29891a087bfc29b21adbaf6f #cat nativebsh.icon
REACT_APP_ICON_BSC_IRC2_TOKEN_ADDRESS=cx21f94683578795b1e0b0b5d492004cfedcad3b6e #cat irc2_token.icon
REACT_APP_ICON_BSC_IRC31_TOKEN=cxf6b2e77dd9d89d9762ae9a3e8eaeae1d2bbd6983 
REACT_APP_ICON_BSC_TOKEN_BSH_ADDRESS=cx57e7a7c30b7b5cffa724fcb17322e19c45b0acc2 #cat token_bsh.icon
```

there is functioning nexus FE on /btp and static balanced btp modal ui on /trade

**Comment by parrot9design** [comment]
@rise-techiast You can find the UI here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/

I think @hetfly has already implemented the UI, but here are the main points:

This is the main transfer modal, which they’ll get to by clicking the `Move assets between blockchains` text link on the Trade page:

transfer-modal

When people choose the network they want to send from, we should display the “Choose wallet” modal for them to authenticate (found under ` Modal: Bridge sign in` in the code):

choose-wallet

I don’t think we’ll show the wallet address in v1 (we haven’t found a good way to display it yet, at least), so to change wallets, you can either click Cancel to close the modal (we should prevent them from being able to click outside the modal to close it, given that will affect the wallet authentication) , or re-choose the network which should resurface the wallet modal.

When you click Transfer, you should see this confirmation message (found under `Modal: Confirm collateral` in the code :sweat_smile:):

confirm-transfer

For the banner messages:

> Transferring {ticker} from {origin network} to {destination network}…

> Transferred {amount} {ticker} to {destination network}.


Let us know if you need any clarification.

**Comment by BennyOptions** [comment]
This will be worked on after LP token staking UI is finished

**Comment by BennyOptions** [comment]
There have been many changes to the BTP UI, so a new PR will be opened

**Comment by sanglt1902** [comment]
Hi @parrot9design @rise-techiast @BennyOptions 
> When people choose the network they want to send from, we should display the “Choose wallet” modal for them to authenticate (found under Modal: Bridge sign-in in the code):

I think users should connect their wallet first because if the user chooses network Moonbeam to ICON, but he/she selects login with ICONex wallet, the network user has already chosen will be incorrect. 

What do you think about that?

**Comment by sanglt1902** [comment]
Hi @parrot9design 

>(found under Modal: Bridge sign in in the code)
(found under Modal: Confirm collateral in the code)

I can't find two modals in this branch. Can you help to check?

**Comment by shallcdn** [comment]
Hi @parrot9design 

>(found under Modal: Bridge sign in in the code)
(found under Modal: Confirm collateral in the code)

I can't find two modals in this branch. Can you help to check?

**Comment by shallcdn** [comment]
@hetfly I see in the source code contains source code of BTP, I'm so confused isn't necessary? Because it has too much change for this PR

**Comment by hetfly** [comment]
@shallcdn it's definitely not necessary. Thats just how I approached the initial merge. I wanted to make it work on balanced app and then clear out unnecessary things. You can continue as you consider appropriate

**Comment by shallcdn** [comment]
@hetfly I got it, btw Do you know about this https://github.com/balancednetwork/balanced-network-interface/pull/936#issuecomment-1107459588

**Comment by hetfly** [comment]
@shallcdn yeah, this is design reference from the prototype here  http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/

You can inspect the code and trigger the modals through the inspector - manually add/remove class ```modal-show``` to the modal wraps, see screenshot
Screenshot 2022-04-23 at 15 59 53

**Comment by shallcdn** [comment]
> When people choose the network they want to send from, we should display the “Choose wallet” modal for them to authenticate (found under Modal: Bridge sign in in the code):

Hi, @parrot9design I'm confused about this flow. I think the user should log in before choosing the network info so that we can get the user's balance value from the wallet. Can you help explain more?

Screen Shot 2022-04-30 at 00 33 49

If the user chooses ICON -> BSC but login with MetaMask. Should we hide MetaMask for this case?

**Comment by parrot9design** [comment]
>Hi, @parrot9design I'm confused about this flow. I think the user should log in before choosing the network info so that we can get the user's balance value from the wallet. Can you help explain more?
>
>If the user chooses ICON -> BSC but login with MetaMask. Should we hide MetaMask for this case?

Let's keep it so that the `Choose wallet` modal appears when they've chosen which network they want to send assets from. We can hide any asset balances until a wallet has been selected. 

If it's possible to only display relevant wallet options for each network, we should absolutely do that to limit the number of edge cases we have to cater for. For example, if a user chooses to send from ICON, Metamask should be hidden. 👍 

Let me know if you need more clarification.

**Comment by BennyOptions** [comment]
Should be about 1 more week. Please make a new PR so we can track.

cc @shallcdn @rise-techiast

**Comment by BennyOptions** [comment]
@rise-techiast expects one more week until a test version, ran into troubles integrating MetaMask

**Comment by hetfly** [comment]
Moved here https://github.com/balancednetwork/balanced-network-interface/pull/978

**Comment by BennyOptions** [comment]
Work moved to PR #980

**Pull request closed without merging**
