### PR TITLE
feat: keep user signed in on refresh

### LINKED ISSUE #122: Keep people signed in on page refresh
You should be able to refresh the page without needing to sign in again. Omm keeps you signed in but has a session expiration time of 30-60min

### PR DESCRIPTION
**Pull request by avipatel91**
1. A hook has been added to persist account address to local storage.
2. ESLint plugin for hooks has versioning bumped due to bug from exhaustive dep rule.

Resolves #122

### CODE REVIEW

**Review by lijac — COMMENTED** [review]
LGTM

**Comment by lijac** [comment]
Can you keep this up with the latest master @avipatel91 ?

**Review by BennyOptions — APPROVED** [review]

**Comment by octocat512** [comment]
@BennyOptions could you test the UX with a ledger?

**Comment by avipatel91** [comment]
> @BennyOptions could you test the UX with a ledger? 

Good call out. I have not verified with ledger.

**Comment by avipatel91** [comment]
Confirmed with ledger.
Test: Refreshed browser.

https://user-images.githubusercontent.com/11547815/155869432-5bccbe53-f5f5-4c20-bd69-1cb04b0aedd3.mov

**Comment by octocat512** [comment]
> @octocat512 Confirmed with ledger. Test: Refreshed browser.
> 
>  ledger.mov
@avipatel91 Could you provide me a video of testing the UI with the following flow again. 
sign in with a ledger. refresh the UI. sign out. refresh the UI. sign in with a web wallet. refresh the UI. sign out. refresh the UI.

**Comment by avipatel91** [comment]
sure.

https://user-images.githubusercontent.com/11547815/155928654-ff97bc0d-09a1-4566-875b-53214d878873.mov

**Comment by BennyOptions** [comment]
@avipatel91 thanks for tackling this! Just noticed that when using Ledger it doesn't let me sign a transaction after refresh.

1.) I sign in with Ledger
2.) I refresh
3.) I remain signed in (good)
4.) I try to execute a transaction, but nothing is prompted on the Ledger (bad)


https://user-images.githubusercontent.com/43685868/156048435-0ce1add0-f5a3-4eb1-b482-b2240c926d8a.mov

**Comment by avipatel91** [comment]
> @avipatel91 thanks for tackling this! Just noticed that when using Ledger it doesn't let me sign a transaction after refresh.
> 
> 1.) I sign in with Ledger 2.) I refresh 3.) I remain signed in (good) 4.) I try to execute a transaction, but nothing is prompted on the Ledger (bad)
> 
>  Screen.Recording.2022-02-28.at.11.44.16.AM.mov

Thanks catching that. I have addressed in latest commit.

I also noticed an existing bug.
Reproduce:
1. Sign in with ledger
2. 'change wallet'
3. select ICON wallet
4. try to execute a transaction. 
5. nothing happens.

Expected: Authorization popup should appear. 

I have fixed that as part of this.

**Comment by avipatel91** [comment]
Test flow

https://user-images.githubusercontent.com/11547815/156138094-b5e1c016-9f8c-4f9d-9230-02fe5458e367.mov


https://user-images.githubusercontent.com/11547815/156138124-952db039-394e-4648-b75f-4336ecf70505.mov

**Comment by lijac** [comment]
I have merged the latest master into this. Does it look good? @avipatel91

**Pull request merged**
