### PR TITLE
Show all pools instead of just the incentivised ones

### LINKED ISSUE #1512: Update the Liquidity Pools section to show all pools, rather than just BALN-incentivised ones
We'll also need to change the section toggle from `Incentivised pools` to `All pools` when signed in.

### PR DESCRIPTION
**Pull request by hetfly**
close #1512

### CODE REVIEW

**Comment by parrot9design** [comment]
I remember now why we didn't do this earlier. Do we really want all of these pools to appear on the page? (cc @FezBox)
Screenshot 2024-10-25 at 12 03 39 PM

Also, how is this pool getting BALN incentives? It's not on the list of pools on the vote page.
Screenshot 2024-10-25 at 11 43 42 AM


In any case, the list is long enough now that we should add a search box to the top right corner.

**Comment by FezBox** [comment]
All key /bnusd pairs should appear there.


Or by default all nol and new chain native asset pairs should be incentivised. Or all those pairs should be there.

We should not have to go to another page to figure out pools when on the supply section of the page

**Comment by parrot9design** [comment]
Ok, so let's go with incentivised pools + NOL and native asset pairs, as that gives us the best coverage to relevance ratio.

That basically means adding INJ/bnUSD, SUI/bnUSD, sARCH/bnUSD, and BNB/bnUSD to the list current in the app, with allowance for any new pools to appear automatically.

**Comment by hetfly** [comment]
@parrot9design updated the list

also @FezBox , when you type in `nol` or `native` in the search box  it shows only NOL pools or pools with native tokens respectively.

**Comment by parrot9design** [comment]
Nice, thanks @hetfly! Wondering if we change `All pools` to `Core pools`, since it's not really all of them now. Otherwise this looks good to go.

I assume the SOL/bnUSD pool will appear under the `native` search term once you can trade it on Solana?

**Comment by hetfly** [comment]
@parrot9design yeah, SOL pool will be there once the SOL PR gets merged. 

I think keeping the tab called `All pools` is fine. In the end it is all the significant pools, perhaps we can include some liquidity filter for the rest of them, maybe > $5k, that would show CROWN, GBET and FRMD, which are still relatively alive projects.

**Comment by parrot9design** [comment]
>I think keeping the tab called All pools is fine. In the end it is all the significant pools, perhaps we can include some liquidity filter for the rest of them, maybe > $5k, that would show CROWN, GBET and FRMD, which are still relatively alive projects.

My main concern is that we'd be acting like the list includes all pools when it doesn't. Even with a filter of >$5k, it would allow pools like IUSDC / bnUSD, sICX / BTCB, and OMM / IUSDC to appear, when they really shouldn't. At least, not unless you have the community token list active.

OMM / sICX probably should be included, though.

**Comment by FezBox** [comment]
Search field makes a huge difference. thank you

**Comment by hetfly** [comment]
>My main concern is that we'd be acting like the list includes all pools when it doesn't. Even with a filter of >$5k, it would allow pools like IUSDC / bnUSD, sICX / BTCB, and OMM / IUSDC to appear, when they really shouldn't. At least, not unless you have the community token list active.

@parrot9design we have a 'token blacklist' setup, tokens on the list won't have their pools shown. IUSDC, BTCB and USDS tokens are there. `Core pools` provides clearer messaging, though, so I don't mind using this label.

**Comment by parrot9design** [comment]
Let's go with `Core pools` for now, we can always adjust later if needed.

Also, currently getting a white screen on the Trade page from the current preview link.

**Pull request merged**
