### PR TITLE
feat: reposition notification for small devices

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Review by parrot9design — APPROVED** [review]
Much better, thanks @hetfly!

**Comment by octocat512** [comment]
Instead of using `useMedia` hook, what about using `react-device-detect`? @hetfly 

https://github.com/balancednetwork/balanced-network-interface/blob/4381d64abb7886c7887506080f4686cd84dbf3f0/src/app/components/Modal/index.tsx#L5

**Comment by hetfly** [comment]
@octocat512  I think this is more of a screen size condition. Under 1000px the notification overlaps with the app navigation. That can happen on resized laptop app window as well.

**Comment by octocat512** [comment]
Make sense @hetfly

**Pull request merged**
