### PR TITLE
feat: Multi-collateral FE

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by hetfly** [comment]
@parrot9design  UI done, please review

**Comment by BennyOptions** [comment]
blocked by other feature upgrades

**Comment by BennyOptions** [comment]
@hetfly please hook these **Berlin contracts** into this pull request and we can begin testing through the frontend

{
    loans: 'cx262f3e27b5c0812016b0ececc34cba04e5d05f08',
    staking: 'cx15e350114b463e3b012781d9609c491615a2fd98',
    dividends: 'cx0d0f87f8ef6a7d129f5f8502e19d0ec3dd8bf151',
    reserve: 'cx8d394cfd7f0a4242b4536b3ddeec9bed9cb6b7c9',
    daofund: 'cxeccfb829ad4f5ae6a42e4bf818565c13f9af8e97',
    rewards: 'cxebab5e7aeff27815e8e1723d806da82fef7dce35',
    dex: 'cx7f1feced586d6dad035ee691dbf98c20e932219d',
    rebalancing: 'cxa7069ac0117ddcfd971bdc925b8222c04ae2abaf',
    governance: 'cx243083912af9d40069e3ba506bcf9b971b1c94b4',
    band: 'cx18f2bc4510f827b0aa9acfe5298d039271e0bb73',
    router: 'cx3365704c07dfafacb92d6d5a3ec83bf94a3f5ab3',
    airdrip: '',
    sicx: 'cxd1ed2e5d5c132574ed8ffa7e141cff2460ab7015',
    bnusd: 'cx0de413b6c9f8ef1086dfb2707b59b5ea8c66d204',
    baln: 'cxbfdbb940fb377c15d3b5ad131e45e24cb28463ef',
    bwt: 'cxb81776403a0d66343b168eb2cbf56db967aa97f3',
    multicall: 'cx4b333a54b2ac5ebdc5f139f66c4a4f7632cc3a61',
    disbursement: 'cxda35146882308a6bb26519738ffef85bb8d7535e',
    stabilityfund: 'cx0d086972db4f23274e80cf19583a76b778216ae4',
    stakedLp: 'cx225c4f25f27d75143a062f4f0928fb01ce642716'
};

**Comment by parrot9design** [comment]
This PR will also need to go out at the same time: https://github.com/balancednetwork/balanced-network-interface/pull/756

Currently reviewing the UX for ^, should have comments for any additional changes by the end of tomorrow.

**Comment by BennyOptions** [comment]
Also I'm sure it's just a placeholder but please remove bnUSD as it's not a collateral type

**Comment by BennyOptions** [comment]
I have a loan but it says "ineligible"

Screen Shot 2022-07-12 at 3 30 37 PM

**Comment by BennyOptions** [comment]
Just to follow up, these contracts are still good for testing

{
loans: 'cx262f3e27b5c0812016b0ececc34cba04e5d05f08',
staking: 'cx15e350114b463e3b012781d9609c491615a2fd98',
dividends: 'cx0d0f87f8ef6a7d129f5f8502e19d0ec3dd8bf151',
reserve: 'cx8d394cfd7f0a4242b4536b3ddeec9bed9cb6b7c9',
daofund: 'cxeccfb829ad4f5ae6a42e4bf818565c13f9af8e97',
rewards: 'cxebab5e7aeff27815e8e1723d806da82fef7dce35',
dex: 'cx7f1feced586d6dad035ee691dbf98c20e932219d',
rebalancing: 'cxa7069ac0117ddcfd971bdc925b8222c04ae2abaf',
governance: 'cx243083912af9d40069e3ba506bcf9b971b1c94b4',
band: 'cx18f2bc4510f827b0aa9acfe5298d039271e0bb73',
router: 'cx3365704c07dfafacb92d6d5a3ec83bf94a3f5ab3',
airdrip: '',
sicx: 'cxd1ed2e5d5c132574ed8ffa7e141cff2460ab7015',
bnusd: 'cx0de413b6c9f8ef1086dfb2707b59b5ea8c66d204',
baln: 'cxbfdbb940fb377c15d3b5ad131e45e24cb28463ef',
bwt: 'cxb81776403a0d66343b168eb2cbf56db967aa97f3',
multicall: 'cx4b333a54b2ac5ebdc5f139f66c4a4f7632cc3a61',
disbursement: 'cxda35146882308a6bb26519738ffef85bb8d7535e',
stabilityfund: 'cx0d086972db4f23274e80cf19583a76b778216ae4',
stakedLp: 'cx225c4f25f27d75143a062f4f0928fb01ce642716'
};

**Comment by parrot9design** [comment]
When ICX/sICX is the active collateral type, I'd prefer to display ICX instead of sICX, as that's the token people are most familiar with and we use the ICX price in the position details section, not sICX. I'm sure not everyone shares that sentiment, though, so happy to be challenged on that. 😅
Screen Shot 2022-08-25 at 12 24 26 PM

---

Can we add an animation to the position details section when it first appears? Right now if you don't have a loan and start using the slider, it sort of just...appears. It'd be nice to ease it in like the liquidity details section, or like it does in the demo.

---

Not sure why this is the case, but it's showing that I wouldn't earn loan rewards for this position?
Screen Shot 2022-08-25 at 12 26 57 PM

Just checked on mainnet, seems to be having the same issue there? All loans should be earning BALN now that we have continuous rewards. 🤔

Also, it seems the LTV for Berlin is different than mainnet, based on the positioning of the `All collateral locked` indicator? Is that easily changed to allow for more accurate testing, or should we just ignore it until we can test on mainnet?
Screen Shot 2022-08-25 at 12 30 39 PM

---

Not sure why, but the collateral selector width changed around a bit as I was testing it, sometimes appearing wider than the collateral section itself, sometimes too thin to display more than a few characters for each column (I had it open while adjusting the browser window size).

For the values here, can we add 2 decimal places rather than rounding down?
Screen Shot 2022-08-25 at 12 45 17 PM

---

For rebalancing, can we display the current ticker, even before the backend is ready to pull through that data? It currently shows sICX when BALN Is the active collateral type:

Screen Shot 2022-08-25 at 12 42 32 PM


On the topic of rebalancing, we'll need to update the liquidity pool in this modal/tooltip for each collateral type:
Screen Shot 2022-08-25 at 12 42 45 PM
Although considering rebalancing hasn't occurred since the Stability Fund went live, maybe we can remove the modal that appears when you first borrow? @BennyOptions any thoughts on this?

---

Not sure what the LTV is set to for BALN (unless this is related to the debt ceiling?), but it doesn't appear to match up with the UI. Unless I do small amounts, I get an error in Hana when borrowing bnUSD and withdrawing collateral.

The amount I was trying to borrow:
Screen Shot 2022-08-25 at 12 58 20 PM

The error received:
Screen Shot 2022-08-25 at 12 58 30 PM

The collateral error occurred when trying to withdraw half of what I had deposited (still far above the Locked indicator):
Screen Shot 2022-08-25 at 12 52 24 PM

---

Not sure if this is related, but when I went to trade some of my bnUSD, the notification messages treated it as though I was borrowing:
Screen Shot 2022-08-25 at 1 05 26 PM

But when I performed the same trade (with different quantities) 5min later, it was back to the normal swap messages?

---

For the token address, let's add the external link icon (used in activity history) to send people to the token contract on the icon.foundation tracker. I think we can keep the ability to copy the address, as well, but no strong preference here.
Screen Shot 2022-08-25 at 1 26 06 PM

**Comment by hetfly** [comment]
@parrot9design updated

> Also, it seems the LTV for Berlin is different than mainnet, based on the positioning of the `All collateral locked` indicator?

 Berlin's at 25% and mainnet's at 66%. I'd leave the visuals testing to mainnet.

> Not sure why, but the collateral selector width changed around a bit

Looks like this is happening only if you go to or from the inspector mode, I wouldn't worry too much about this happening to our users.

> For the values here, can we add 2 decimal places rather than rounding down?

Sure, but at higher amounts it seems a bit cluttered:
image

cc @BennyOptions 
Regarding the wallet errors and marginal cases for borrow/withdraw/repay I'd much rather take care of it on mainnet.
I'm thinking we could do a separate PR for collateral proposals, after one passes we test everything in this PR, polish things up and merge a while later.

**Comment by BennyOptions** [comment]
Plan:

Once a new collateral type is approved on main net, let's set this PR to main net, test UX internally, then merge.

**Comment by BennyOptions** [comment]
@shallcdn as a priority, please review this PR. It is a big feature upgrade, thanks!

**Comment by BennyOptions** [comment]
@hetfly please resolve conflicts as well.

**Comment by parrot9design** [comment]
@hetfly, looks like the messages in the ICX withdraw modal have been flipped. I was a little confused to see the sICX message after I clicked `Unstake`. 😅

Screen Shot 2022-09-21 at 1 58 22 PM
Screen Shot 2022-09-21 at 1 58 10 PM

**Comment by parrot9design** [comment]
This is looking pretty good overall. Just found a few non-critical issues to fix.

If you have the loan in edit mode, then switch the collateral type, the loan section stays in edit mode. This can be quite confusing, especially if you switch to a collateral type that doesn't have an open loan yet. When switching between collateral types, we should revert it to a read-only state.

https://user-images.githubusercontent.com/63842577/191657126-feb62ad4-0db7-42d3-bda6-c9da402acb68.mov

---

If you try typing into the Borrowed field, you're first interrupted by the `10 bnUSD minimum` tooltip, and then by the slider, so you have to click back into the field to keep typing. This only happens in the Borrowed field, and is fine in the current production version.

https://user-images.githubusercontent.com/63842577/191657718-ab2473a7-7874-4628-a92b-9f290547b865.mov


---

Let's remove the Rebalancing modal that appears when you borrow for the first time:
Screen Shot 2022-09-22 at 3 34 32 PM
This is less of an issue now that we have the Stability Fund to maintain balance, and we'll be replacing rebalancing with something else soon.

---

Add comma separation to the price under `All collateral locked`:
Screen Shot 2022-09-22 at 3 41 20 PM

---

If you use the slider to borrow the maximum amount (for either collateral type), the collateral and position details sections act like you still have room to borrow more:
Screen Shot 2022-09-22 at 3 33 51 PM
Screen Shot 2022-09-22 at 3 31 15 PM

But if you type `0` into the Available field, they show that it's maxed out:
Screen Shot 2022-09-22 at 4 10 31 PM

---

Slight rounding difference between the available loan value in the collateral dropdown and loan section:
Screen Shot 2022-09-22 at 3 33 10 PM Screen Shot 2022-09-22 at 3 31 51 PM

---

If you try to withdraw all your collateral after closing out a loan, the transaction won't go through. I see this error in Hana, and had to leave 3 ICX behind before I could authorise the transaction:
Screen Shot 2022-09-22 at 3 48 04 PM

**Comment by hetfly** [comment]
@parrot9design fixed.

> If you use the slider to borrow the maximum amount (for either collateral type), the collateral and position details sections act like you still have room to borrow more

The difference between typing and sliding is fixed but there needs to be a few dollars cushion because of the loan fees, that's why the wallet throws an error. It's visually more significant at lower collateral amounts and gets quickly irrelevant. This is how it looks for ~ $1k collateral:
image

**Review by parrot9design — APPROVED** [review]
Let's get this merged! 💪

**Comment by AntonAndell** [comment]
> The difference between typing and sliding is fixed but there needs to be a few dollars cushion because of the loan fees,

Not super necessary but you could calculate it quite easy by fetching the fee Percentage from the loans contract.

**Pull request merged**
