### PR TITLE
Feat/remove ledger

### PR DESCRIPTION
**Pull request by swiftcc624**

### CODE REVIEW

**Comment by parrot9design** [comment]
It's smooth to connect an ICON wallet through the main sign-in / manage wallets modal, but if you try to connect an ICON wallet from anywhere else (Collateral section, Trade page), nothing happens:

https://github.com/user-attachments/assets/d9fd57bd-d3f0-4388-9613-627152dfa954

**Comment by swiftcc624** [comment]
@parrot9design I fixed connecting icon wallet on swap, collateral sections.

**Comment by parrot9design** [comment]
It works well on the Trade page now, thanks! Nothing happens if you click `Sign in with ICON` in the Collateral section, though.

**Comment by swiftcc624** [comment]
@parrot9design Sorry, I mis-understood collateral section, I fixed it.

**Comment by parrot9design** [comment]
Thanks @swiftcc624! Just discovered one more:

Screenshot 2024-08-16 at 4 27 01 PM

**Pull request merged**
