### PR TITLE
Feat/multicall

### LINKED ISSUE #948: Implement MultiCall Contract to Frontend

### PR DESCRIPTION
**Pull request by lijac**
Close #948

### CODE REVIEW

**Comment by lijac** [comment]
- [ ] Set Dex address of Multicall contract and update code accordingly.
- [ ] Deploy to mainnet.

**Comment by octocat512** [comment]
blocked by the [PR](https://github.com/balancednetwork/balanced-java-contracts/pull/74)

**Comment by lijac** [comment]
Test:

Error
image
image

Error
image
image

Ok
image

**Comment by nightowl121** [comment]
Readonly calls also have step limit, you can't do everything in a single readonly call.

**Pull request merged**
