### PR TITLE
Cross chain loan enhancements

### LINKED ISSUE #1401: Cross-chain loan enhancements
- [x] Add list sorting to the collateral & blockchain selectors.
- [x] When signed in, order both lists in the collateral section from highest to lowest collateral deposited, then by highest to lowest balance available. Sort the loan blockchain selector by wallet balance.

<br>

- [ ] Add the chain breakdown for each collateral type in the signed out & `All collateral` states:
Screenshot 2024-08-19 at 1 28 49 PM

- [x] Update the zero balance view in the Collateral section to prompt users to add the token to their wallet:
update-0-balance-state

>Add {token} to your {blockchain} wallet.

<br>

- [x] The above screenshot was taken in Firefox. Is there any way to fix the alignment of icons and chevrons on the Home page? Also noticed it on the Trade page, but to a lesser extent.

<br>

- [x] When you click to adjust your collateral/loan, the Confirm button should be inactive until there's a change in balance so that you can't complete empty transactions.
https://github.com/user-attachments/assets/d0d1869f-688f-4774-9d83-35a80ce7900e

<br>

- [x] Hide the blockchain address in the borrow confirmation modal if you choose to receive bnUSD on the same chain.

<br>

- [x] Update the confirmation modals to use `Transfer fee` instead of `Cross-chain fee`:
Screenshot 2024-08-19 at 4 03 05 PM

<br>

- [x] This applies to the whole app, but when you first visit a page, it takes a while for the fonts etc to load in. Is there anything we can do to speed this up?

<br>

- [x] When you choose to withdraw ICX collateral, make `Keep sICX` the default and change `recieve` to `receive`:
Screenshot 2024-08-22 at 5 40 45 PM

<br>

- [x] Update the social image for the app (https://app.balanced.network/img-preview/home.png) to this one: [home.png.zip](https://github.com/user-attachments/files/16860709/home.png.zip)

<br>

- [x] Update the sign in message in the Collateral section (`... sign in with {chain}.` -> `...sign in on {chain}.`
update-sign-in-prompt

<br>

- [x] Prevent the borrow fee in the modal from resetting to `0 bnUSD` after you sign the transaction

<br>

- [x] After you click Connect for a chain in the Loan section, that blockchain should become the active one.
https://github.com/user-attachments/assets/d8b812ef-4145-4cef-bb05-97c6612f9393

<br>

- [x] If a transaction has to roll back, let's change the modal message from `Transfer rollbacked` to `Transaction reverted`

### PR DESCRIPTION
**Pull request by hetfly**
close #1401

### CODE REVIEW

**Comment by parrot9design** [comment]
Thanks for humouring me with all these fixes. Just found a couple things to address.

- [ ] Is there any way to prevent the collateral selector from initially loading like this after you load the page?
Screenshot 2024-10-25 at 4 03 32 PM

<br>

- [ ] When your risk is at/past the `All collateral locked` level, can we make the collateral & loan values red in the collateral selector?
Screenshot 2024-10-25 at 4 07 26 PM

<br>

- [ ] Still noticing this issue for some assets:
>When you click to adjust your collateral/loan, the Confirm button should be inactive until there's a change in balance so that you can't complete empty transactions.
https://github.com/user-attachments/assets/f8804470-9ba8-4b67-a2cb-1349592bf6c9

<br>

- [ ] ICX doesn't appear as an option in the collateral selector, even though I have enough in my wallet

<br>

- [ ] The social image still appears to use the old one, not the one that shows cross-chain loans?

<br>

- [ ] The blockchain in the loan section doesn't always connect as expected, especially if the chains between sections are different when you sign out. (Allows you to have a chain active in the loan section that isn't connected, and connects to a random chain when you choose an EVM option):
https://github.com/user-attachments/assets/d435cf7d-9011-4f35-be27-cd3afe9e109e

<br>

I think the fix you've implemented for the fonts works well, it's much harder to force a state where I see the system default and even then, it's only for a split second.

**Comment by hetfly** [comment]
>the collateral selector from initially loading like this after you load the page

@parrot9design is this still happening? I couldn't replicate the issue.

>The social image still appears to use the old one, not the one that shows cross-chain loans?


Earlier we switched the preview image URL to be absolute, so you can't see the new image, even if you use this deployment's url. Once it's merged, the image will be replaced.

https://github.com/balancednetwork/balanced-network-interface/pull/1447/files#diff-103229ac3a142e54af6062790b11bc8b5a3247b19a7082cb8dfbe842070c1cbc


> ICX doesn't appear as an option in the collateral selector, even though I have enough in my wallet

how much do you have? ICX threshold is set quite high (~ 5 I think) to make sure users have couple crosschain txs in the bank.

**Comment by parrot9design** [comment]
>> the collateral selector from initially loading like this after you load the page
>
>@parrot9design is this still happening? I couldn't replicate the issue.

Yep, I see this on every device/browser, even when content blockers are turned off.

Here's Firefox:

https://github.com/user-attachments/assets/cb7b7326-8469-418a-a905-3b90f2126b13

Safari:

https://github.com/user-attachments/assets/eb7967ed-3177-4e41-b21f-6c0ebf525f71

---

>> ICX doesn't appear as an option in the collateral selector, even though I have enough in my wallet
>
>how much do you have? ICX threshold is set quite high (~ 5 I think) to make sure users have couple crosschain txs in the bank.

I tried it with a wallet that has 3,000 ICX in it, but it doesn't appear as an option. If I choose ICX from the `All collateral` tab, it loads with my ICX balance so I can deposit, but I have 0 sICX so have to assume it's trying to pull from that value instead (ideally it should combine both)?

---

Also, it never wants to cooperate for a screen recording, but I'm constantly having to click the sliders 2-3 times before I can actually drag them. Someone else has reported this as an issue to me, as well. Is there anything we can do to address it?

**Comment by hetfly** [comment]
>I tried it with a wallet that has 3,000 ICX in it, but it doesn't appear as an option. If I choose ICX from the All collateral tab, it loads with my ICX balance so I can deposit, but I have 0 sICX so have to assume it's trying to pull from that value instead (ideally it should combine both)?

@parrot9design ICX is now shown as a standalone potential position, if there is no sICX collateral already deposited. Combining them would be a workaround, I think at some cases even confusing. The positions are split on user's ICX/sICX balances in their wallet anyways, I'd prefer to keep them separate in the selector, as well. You can see both potential positions, if you have no sICX collateral deposited and have both ICX and sICX in your wallet.

image

**Comment by parrot9design** [comment]
- [ ] Can we align the asset with the collateral & loan values? Looks like it's floating on its own a bit.
Screenshot 2024-10-30 at 3 43 39 PM

<br>

- [ ] If you're not connected to the active chain in the Collateral section when you try to change the blockchain in the Loan section, the active chain won't change after you connect your wallet:

https://github.com/user-attachments/assets/b5b10653-934e-4fbc-9b11-5b4034b6ea16

---

Interesting handling for the ICX/sICX collateral, I quite like being able to avoid the confusion of combined balances. 💪 

- [ ] After you deposit ICX/sICX, the `Your collateral` tab will only show the balance in sICX. Can we make it like the `All collateral` tab, which shows either ICX or sICX depending on which asset is active in the toggle?

Screenshot 2024-10-30 at 4 12 18 PM

 

<br>

Also, I assume merging this PR won't automatically ship the Stellar connection, or do we need to wait until that's live?

**Comment by hetfly** [comment]
>Also, it never wants to cooperate for a screen recording, but I'm constantly having to click the sliders 2-3 times before I can actually drag them. Someone else has reported this as an issue to me, as well. Is there anything we can do to address it?

Happens to me sometimes too, but it's ridiculously difficult to debug. It's likely to do with multiple app rerenders caused by different data fetching. Something only general optimisation might solve, I think. We can plan a task for performance optimisation and try to fix it, but it might also be just a waste of time.

<hr />

>Also, I assume merging this PR won't automatically ship the Stellar connection, or do we need to wait until that's live?

Unfortunately, it will, I assumed the Stellar PR will be long merged by now 😅

**Comment by parrot9design** [comment]
- [ ] If the last asset in your wallet is on multiple chains, let's remove the border underneath the breakdown:
Screenshot 2024-10-31 at 4 53 59 PM

Otherwise, this looks ready to ship (as soon as Stellar is live 😅). Thanks for all your work on this, @hetfly. 🙏

**Review by parrot9design — APPROVED** [review]

**Comment by parrot9design** [comment]
One final thing: can we update the app description?

>A cross-chain DeFi app crafted for simplicity. Borrow bnUSD, swap crypto, supply liquidity, transfer between chains, earn rewards, and participate in governance.

**Comment by parrot9design** [comment]
Thoughts on increasing the logo sizes on the Home page?

When looking at the Solana PR, I was worried that the logo was harder to see than it should be, so I tried a new variation that uses 24px for the asset, 20px for the blockchain:

Original | Updated
------- | ---------
Screenshot 2024-11-20 at 10 28 19 AM | Screenshot 2024-11-20 at 10 27 56 AM

**Comment by parrot9design** [comment]
Ok, final thing (I swear 😅):

Can we prevent non-ICON assets from appearing interactive in the wallet? 
Screenshot 2024-11-28 at 7 44 13 AM

**Pull request merged**
