### PR TITLE
fix: precision of loan amount

### PR DESCRIPTION
**Pull request by hieunguyenebox**

### CODE REVIEW

**Comment by hieunguyenebox** [comment]
Screen Shot 2021-07-16 at 21 53 16

**Comment by hieunguyenebox** [comment]
@BennyOptions please review

**Comment by BennyOptions** [comment]
@tuan-tl please review today

**Comment by WeiLi512** [comment]
Could you explain how you solved the issue? @hieunguyenebox I can't understand your solution.

**Pull request merged**
