### PR TITLE
feat: show wallet button in all sizes

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by parrot9design** [comment]
If I tap the address to copy it, then scroll down the page, the `Copied` message follows:
IMG_441460E4BB10-1

When I try this in a Brave window below 800px, the start of the wallet address is overlapped:
Screen Shot 2022-04-25 at 8 51 32 AM
(can't reproduce on mobile, though 🤔)

Other than that, this is good!

**Review by parrot9design — APPROVED** [review]
Looks good, thanks @hetfly!

**Comment by octocat512** [comment]
@hetfly @parrot9design  The `Copied` text is suddenly shifted to the center whenever clicking the address text after opening the menu.

**Comment by hetfly** [comment]
@octocat512 that's intended. But I guess there is enough space even on 320px screens so we can keep it on the left.

**Pull request merged**
