### PR TITLE
feat: add icx/sicx collateral management

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by hetfly** [comment]
Seems like ICX/sICX ratio isn't working properly on Sejong, that's why both collateral amounts are the same number.

@parrot9design please provide explanation text for switcher tooltip.
@octocat512 I need help with merging. When I try it locally there are some errors in loan hooks, can you check that out please ?

**Review by parrot9design — APPROVED** [review]
This is fantastic, thanks for your hard work @hetfly. 🙏

Just left a couple of suggestions for the capitalisation of `Staked ICX`. Other than that, this is good from a UX perspective.

**Comment by BennyOptions** [comment]
blocked, waiting to refactor for multiple collateral types

**Comment by BennyOptions** [comment]
@octocat512 can you discuss with @hetfly about how we can get this merged? Multi-collateral in production will take a couple months I think

**Comment by BennyOptions** [comment]
@octocat512 after looking at other PRs, please look into this PR and provide guidance on next steps

**Comment by octocat512** [comment]
@hetfly Please resolve the conflicts.

**Comment by hetfly** [comment]
@octocat512 resolved
@parrot9design please review again to be sure

**Comment by parrot9design** [comment]
Looks good at desktop! At mobile it's harder to judge as it doesn't include the enhancements from https://github.com/balancednetwork/balanced-network-interface/pull/882. We should push #882 before this PR, so let's make sure to merge in the changes from that branch.

**Comment by BennyOptions** [comment]
@hetfly please resolve conflicts

@octocat512 please consider how to simplify the code if you feel it is too complex

**Comment by BennyOptions** [comment]
@hetfly just another tag to please resolve conflicts when you get the chance

**Comment by hetfly** [comment]
@BennyOptions @octocat512 resolved

**Review by parrot9design — APPROVED** [review]

**Comment by BennyOptions** [comment]
waiting for multiple collateral types

**Comment by parrot9design** [comment]
Will review this over the next 24 hours and let you know of any changes to enhance the UX further.

**Comment by parrot9design** [comment]
When withdrawing collateral while in the ICX state, let's display an alternative withdrawal modal. This will provide more context for people viewing it in this state, as they won't see the ICX they've withdrawn as available to deposit after the transaction has been completed.

 

- If they keep sICX, switch to the sICX view after the transaction has been completed.
- If they unstake ICX, stay in the ICX view.

```
<div id="modal-withdraw-collateral" class="modal modal-show">
	<div class="modal-content">
		<!-- Overview -->
		<h3 class="label text-center">Withdraw ICON collateral?</h3>
		<p class="text-bold text-center">125 ICX</p><p class="label text-center">– 98 sICX</p>

		<!-- Comparison -->
		<div class="grid comparison">
			<div class="grid-cell text-center border-right">
				<p class="label">Before</p>
				<p>1,000 ICX</p>
			</div>

			<div class="grid-cell text-center">
				<p class="label">After</p>
				<p>875 ICX</p>
			</div>
		</div>

		<!-- Message -->
		<p class="label text-center">Your ICX is staked (sICX). Choose what to do with it:</p>

		<!-- Withdraw options -->
		<div class="grid graphical-options">
			<div class="grid-cell text-center">
				<input class="checkbox-tools" type="radio" name="tools" id="tool-1" checked=" ">
				<label class="for-checkbox-tools" for="tool-1">
					<img class="svg" src="../img/icon/timer-color.svg">
					<br>
					<span class="text-bold">Unstake</span>
					<br>
					<span>125 ICX</span>
				</label>
			</div>

			<div class="grid-cell text-center">
				<input type="radio" name="tools" id="tool-2" class="checkbox-tools" checked="">
				<label class="for-checkbox-tools" for="tool-2">
					<img class="svg sicx" src="../img/icon/wallet-tick-color.svg">
					<br>
					<span class="text-bold">Keep sICX</span>
					<br>
					<span>98 sICX</span>
				</label>
			</div>

		</div><p style="margin-top: 10px;" class="label text-center">Takes up to 7 days. When it's ready, you can claim your unstaked ICX from the wallet section.</p><p style="margin-top: 10px;" class="label text-center hide">Receive sICX, which you can trade or unstake from the wallet section later.</p><!-- Modal actions -->
		<div class="modal-actions">
			<a href="#" class="cancel modal-close">Cancel</a> <a href="./" class="button">Withdraw</a>
		</div>
	</div>
</div>
```

We did have the design for a third option, `Swap now`, but this isn't essential to include as it may introduce more problems if people don't read it properly ("Why do I have 1% less ICX?!").

**Comment by hetfly** [comment]
@parrot9design it's not possible to withdraw collateral and unstake it in one transaction. Omm smart contract has a withdraw method parameter that determines whether user wants to wait for unstaked ICX or recieve sICX.

@BennyOptions how much effort would be to add something similar to `withdrawCollateral` method?

**Comment by hetfly** [comment]
merged into https://github.com/balancednetwork/balanced-network-interface/pull/821

**Pull request closed without merging**
