### PR TITLE
Feat: add bbaln UI

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by parrot9design** [comment]
Nice progress so far!

Some preliminary feedback: 

Activity history should be below the Rewards section:
Screen Shot 2022-01-24 at 3 25 46 PM


Let's remove the message in this modal:
Screen Shot 2022-01-24 at 3 27 54 PM


Let's remove this tooltip:
Screen Shot 2022-01-24 at 3 29 47 PM


Not fond of this white space in this state, but I don't know if we can do anything about it until you earn network fees.
Screen Shot 2022-01-24 at 3 28 28 PM
Also: 
- bBaln -> bBALN
- In an empty state, network fees would be 0.00%, and loan and liquidity rewards set to 1x.


Screen Shot 2022-01-24 at 3 41 08 PM
- Rewards should have a lowercase _r_ : `Max rewards`

**Comment by hetfly** [comment]
@parrot9design updated,
about the whitespace you mentioned 
a) we can hide the boosting info if user has 0 bALN
b) we can move tooltip text from Boost rewards 0 bBALN ```?``` underneath the claiming buttons, similarly as it is in position details:
image
c) leave it as is, seems like the best option from all these

**Comment by octocat512** [comment]
blocked until the continuous rewards contract Java migration.

**Comment by hetfly** [comment]
Moved here https://github.com/balancednetwork/balanced-network-interface/pull/978

**Pull request closed without merging**
