### PR TITLE
fix: optimise performance

### LINKED ISSUE #1040: Reconsider/Refactor Stability Fund UX
App goes extremely slow when a stability-fund pair is selected. Either find a way to refactor the FE to make this smoother or reconsider the design for a smoother UX. I took a video but it's too big to attach here. We can discuss on FE call, but high level issues below:

1.) Takes much longer to load the swap
2.) Takes at least a few seconds to load the stability fund popup
3.) Using any other part of the interface while a stability fund pair is selected is laggy/glitchy compared to non-stability fund pairs

### PR DESCRIPTION
**Pull request by hetfly**
close #1040

### CODE REVIEW

**Comment by BennyOptions** [comment]
Are network fees hooked up properly @hetfly? I didn't see any fees to claim with this wallet, but there should be.

Screen Shot 2022-07-25 at 12 48 03 AM

**Comment by BennyOptions** [comment]
Besides network fees, it works great. Much better!

**Comment by BennyOptions** [comment]
Ah, one more issue. The banner is the old banner. Need to switch back to banner about network fees.

Screen Shot 2022-07-25 at 12 59 07 AM

**Review by octocat512 — APPROVED** [review]
looks good

**Pull request merged**
