### PR TITLE
feat: add sICX

### PR DESCRIPTION
**Pull request by 0xmilktea**

### CODE REVIEW

**Comment by 0xmilktea** [comment]
add sICX in hswap as well.

**Comment by 0xmilktea** [comment]
remove sICX in xChainMap data structure.

**Comment by FezBox** [comment]
https://github.com/balancednetwork/balanced-java-contracts/issues/442
for baln to be added as well

**Comment by FezBox** [comment]
@0xmilktea have you added baln for the same chains as well?

**Pull request closed without merging**
