### PR TITLE
Feat/add sui tokens

### PR DESCRIPTION
**Pull request by swiftcc624**

### CODE REVIEW

**Comment by parrot9design** [comment]
- [ ] When you click one of the Sui tokens from the `All collateral` view, they default to the ICON blockchain. They should default to Sui.

- [ ] When I try to deposit haSUI or vSUI collateral, I get a `Failed signing` error in Hana wallet and can't go any further. This probably also happens with afSUI, but I ran into an error trying to get some so I haven't been able to test it yet.

**Comment by swiftcc624** [comment]
@parrot9design I fixed the formatting of symbols - afSUI and it will be default to Sui.

>When I try to deposit haSUI or vSUI collateral, I get a Failed signing error in Hana wallet and can't go any further. This probably also happens with afSUI, but I ran into an error trying to get some so I haven't been able to test it yet.

I think it's related to Hana Wallet.

**Comment by parrot9design** [comment]
The formatting is fixed in the collateral dropdown, but it's still all-caps everywhere else:
Screenshot 2024-11-13 at 6 45 40 PM

---

>>When I try to deposit haSUI or vSUI collateral, I get a Failed signing error in Hana wallet and can't go any further. This probably also happens with afSUI, but I ran into an error trying to get some so I haven't been able to test it yet.
>
>I think it's related to Hana Wallet.

I set up Suiet to verify, but it's actually a problem there too. What wallet were you testing with that allowed it to work?

Here was the message it provided:
>Dry run failed, could not automatically determine a budget: MoveAbort(MoveLocation { module: ModuleId { address: a3c66ac08bca78a475954683a872a296fd61a28d478c4a8ebce676fc38f502d6, name: Identifier("asset_manager") }, function: 27, instruction: 8, function_name: Some("enforce_version") }, 8) in command 2 (code: -1)

**Comment by swiftcc624** [comment]
I am using Sui wallet, https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil

**Comment by swiftcc624** [comment]
@parrot9design I fixed formatting symbol

**Comment by swiftcc624** [comment]
@parrot9design I fix the issue with Hana Wallet, it should work now.

**Comment by swiftcc624** [comment]
@parrot9design I fixed formatting symbol

**Comment by parrot9design** [comment]
Screenshot 2024-11-14 at 4 00 49 PM

**Comment by swiftcc624** [comment]
@parrot9design sorry, i fixed it as well

**Comment by parrot9design** [comment]
Thanks @swiftcc624.

I noticed that they show as empty in the `All collateral` section, even after I've opened a position:

Screenshot 2024-11-14 at 4 53 01 PM Screenshot 2024-11-14 at 4 53 28 PM

Screenshot 2024-11-14 at 5 04 53 PMScreenshot 2024-11-14 at 5 04 47 PM


Once we get that fixed, it should be good to merge.

**Comment by swiftcc624** [comment]
@parrot9design I fixed the value in All collateral tab.

**Pull request merged**
