### PR TITLE
Fix: Sometimes ledger load address list of first page on other pages

### PR DESCRIPTION
**Pull request by nviethuan**

### CODE REVIEW

**Comment by BennyOptions** [comment]
This is what I see when logging in, the addresses never finish loading. It gets stuck.
Screen Shot 2021-11-30 at 7 54 13 PM

**Comment by rise-techiast** [comment]
> This is what I see when logging in, the addresses never finish loading. It gets stuck.
> Screen Shot 2021-11-30 at 7 54 13 PM

Adjusted to Sejong, can you please check again now @BennyOptions ?

**Comment by BennyOptions** [comment]
The issue in my prior comments is fixed, however, the primary bug still occurs, see screenshots below. Here is how to recreate the issue:

1.) login with ledger
2.) go to page 3
3.) select on address on page 3
4.) Click the wallet widget then click "Change wallet"
5.) Select ledger
6.) When ledger comes up, it will be on page 3 but it will be displaying page 1 addresses.

Screen Shot 2021-12-15 at 5 57 21 PM

Screen Shot 2021-12-15 at 5 54 43 PM

**Review by BennyOptions — APPROVED** [review]
UX works

**Comment by BennyOptions** [comment]
@rise-techiast please resolve conflicts

**Pull request closed without merging**
