### PR TITLE
Feat: implement message banner

### PR DESCRIPTION
**Pull request by Chunn**

### CODE REVIEW

**Comment by parrot9design** [comment]
Let's always align the banner with the main grid. Between 1000px - 1450px it's too narrow, and above 1450px it's too wide:

1000px - 1450px:
Screen Shot 2022-02-22 at 12 25 06 PM

Above 1450px:
too wide

Preferred:

aligned with grid

---

Also, I wonder if we should merge this into the continuous rewards branch instead of master, as we won't need this banner until those changes are published.

**Comment by parrot9design** [comment]
This is looking great, thanks @Chunn!

>Ok. I'll change the target branch. Is it the reward-distribution branch?

Let's put it into the `fix/staking-lp` branch, as the main changes the banner message mentions are in this PR: https://github.com/balancednetwork/balanced-network-interface/pull/770

**Review by parrot9design — APPROVED** [review]

**Comment by octocat512** [comment]
The banner is for staking LP. So it is blocked until the contract upgrade.

**Comment by octocat512** [comment]
Thanks @Chunn 
I will merge the PR with disabling the message notification.

**Pull request merged**
