### PR TITLE
deploy airdrip page as a PR

### LINKED ISSUE #910: Deploy Goodwill collection frontend
Need to deploy a frontend for users to claim their goodwill collections

### PR DESCRIPTION
**Pull request by octocat512**
close #910

### CODE REVIEW

**Comment by parrot9design** [comment]
Let's change the main content to:

> # Goodwill disbursement
>If you were a borrower on Balanced between January 20 - 24, you’re eligible to claim sICX as a gesture of goodwill. [View proposal details.](https://gov.balanced.network/t/emergency-fund-goodwill-blackswan-event-refine-proposal/759/141)


- [ ] Remove the Airdrip logo
- [ ] Remove the Airdrip animations
- [ ] Paragraph text size: 20px
- [ ] Paragraph text colour: `rgba(255,255,255,0.75)`
- [ ] Link text colour: `rgb(47, 204, 220)`
- [ ] Paragraph max width: 500px

Screen Shot 2022-03-02 at 1 26 42 PM

---

For the panels, we can remove the left-hand content so we're left with these variations:

Screen Shot 2022-03-02 at 1 19 14 PM

Screen Shot 2022-03-02 at 1 19 20 PM

- [ ] Make sure the button content is updated from `Claim airdrip` to `Claim sICX`

Screen Shot 2022-03-02 at 1 19 24 PM

- [ ] Make sure the `Airdrip claimed` message is updated to `sICX claimed`

**Comment by octocat512** [comment]
cxe3905591929d17fc8496ae28ee3b9c144579228e

**Comment by BennyOptions** [comment]
getDisbursementDetail - to display to users
claim - to have the user claim their rewards (no parameters)

**Comment by BennyOptions** [comment]
This address is not eligible to claim, however, the UI says "sICX claimed". It was not claimed, this address was not eligible. It is not on the list.

Screen Shot 2022-03-02 at 6 36 18 PM

**Comment by BennyOptions** [comment]
Also, can we please do 2 decimal places for all numbers? so 25.00 as an example

**Comment by octocat512** [comment]
> 

The UI shows as `sICX claimed` if the claimable token amount is zero.

**Comment by parrot9design** [comment]
Looks good! Just need to fix the banner messages:
Screen Shot 2022-03-03 at 4 47 45 PM
- Change to `Claiming sICX...`

---
Screen Shot 2022-03-03 at 4 47 51 PM

- Change to `sICX claimed.`

**Review by parrot9design — APPROVED** [review]
I can no longer test claiming as I ran out of eligible wallets, but as the only feedback I had was related to the banner messages, this should be good to go.

**Comment by BennyOptions** [comment]
only change I still would like is if you can add two decimal places @octocat512

**Pull request merged**
