### PR TITLE
fix: fix proposal time remaining

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by BennyOptions** [comment]
This looks correct

**Comment by BennyOptions** [comment]
Actually, there are still issues. I can't narrow down exactly *when* the issue starts, but at some point, the current production branch becomes correct and this branch becomes incorrect. This is why we added the "-1" in the first place, because it appeared to fix the issue. Please see below, the vote actually starts in 17 hours.

Production Branch
Screen Shot 2022-02-23 at 4 59 47 PM

This branch
Screen Shot 2022-02-23 at 4 59 18 PM

**Comment by hetfly** [comment]
Needs to be tested on mainnet proposal before merging

**Comment by parrot9design** [comment]
@hetfly, when you're able to revisit this, can you format the time remaining and % required strings for translation?

162895129-59a63a7a-a012-4632-baae-e15be53f0e42

(Originally mentioned in #945.) 

For reference, check out [this PR](https://github.com/balancednetwork/balanced-network-interface/pull/947/files).

**Comment by hetfly** [comment]
Sure

**Comment by BennyOptions** [comment]
@hetfly unfortunately this is not accurate for this current proposal, at least before it starts

**Comment by BennyOptions** [comment]
@hetfly just checking in on this PR, let me know what the current status is

**Comment by hetfly** [comment]
@BennyOptions there has been two things.
1) bug with time left, thats resolved.
2) after localising the app, there was an inconvenience with translating the time left string. We changed that dynamic string to the format that will fit all the supported languages: Voting starts in 2d 12h 21m / Voting ends in 6h 13m. 

I just want to test it on an upcoming proposal to be sure.

**Comment by BennyOptions** [comment]
@hetfly there is now a new proposal. Please check it, and it it's good, we can merge. Leave your comment here for @octocat512, I believe he would need to merge it

**Comment by hetfly** [comment]
@octocat512 @BennyOptions it's good to merge

**Pull request merged**
