### PR TITLE
fix: minimum to receive

### LINKED ISSUE #796: Typing in "for" section always results in failed transaction
The minimum to receive param does not update properly when typing in the "For" section of the swap. It always sets minimum to receive as the exact amount in the "For" section. All user trades will revert if they type in the "For" section

Transaction: https://tracker.icon.foundation/transaction/0xd613048bea30259a6030acf9144e0a9cff8c2a402425d779eb6e8a3be4f273f7

### PR DESCRIPTION
**Pull request by octocat512**
close #796

### CODE REVIEW

**Comment by octocat512** [comment]
@lijac If the pair is the sICX/ICX queue, all txs are failed. How can we solve the issue?

**Comment by octocat512** [comment]
sICX -> ICX
https://tracker.icon.foundation/transaction/0x3194e15f2f9bc57ac61b156aaed40dacc29c7cbc42ba7c175cd4a01e8897f8f4
ICX -> sICX
https://tracker.icon.foundation/transaction/0xdbcb362ea17a93b862c6246ac719b9047d60ee06f7afc4fa790dfa296f139c4b

I tried to convert sICX to ICX, the tx didn't use the router contract.
I tried to convert ICX to sICX, the tx used the router contract.

**Review by lijac — COMMENTED** [review]
LGTM

**Comment by octocat512** [comment]
> @lijac If the pair is the sICX/ICX queue, all txs are failed. How can we solve the issue?
> 
> Reproduce method: Input the value in the for section(ICX input) and submit the tx. then it is failed.
> 
> https://www.loom.com/share/77e352a724264605a272c8a9166a5cc0

what about the issue? @lijac

**Comment by lijac** [comment]
It doesn't happen on the current deployment - https://balanced-network-interface-fygrlbn55-balanced-dao.vercel.app/

**Comment by lijac** [comment]
I got what you mean, sICX -> ICX swap using the For section isn't affected by this PR actually, because this PR affects only non-queue pairs.
The issue in the above loom video is a very rare case. It can only happen when sICX/ICX ratio changes.

**Pull request merged**
