### PR TITLE
Adjust the price chart time frames on the Trade page

### PR DESCRIPTION
**Pull request by shallcdn**
- [x] Add  '1W' to chart period

### CODE REVIEW

**Comment by octocat512** [comment]
Why the PR is blocked? The price chart API doesn't support the 1W period? @shallcdn

**Comment by shallcdn** [comment]
> Why the PR is blocked? The price chart API doesn't support the 1W period? @shallcdn

Yes, that's right!

**Comment by octocat512** [comment]
@shallcdn The API is ready.

**Comment by shallcdn** [comment]
> @shallcdn The API is ready.

I have checked it but it looks like don't work, BE need to be resync data again

https://iconcommunity.slack.com/archives/G0117R69JK0/p1646948139828569

**Comment by octocat512** [comment]
@pranav925 could you check the issue?

**Comment by BennyOptions** [comment]
@shallcdn backend API should be completed now

**Comment by shallcdn** [comment]
@octocat512  I have checked the API, and it works well, please take a look
Screen Shot 2022-03-23 at 11 07 50

**Pull request merged**
