### PR TITLE
Feat/solana

### PR DESCRIPTION
**Pull request by swiftcc624**

### CODE REVIEW

**Comment by parrot9design** [comment]
- [ ] Can we add a `No Solana wallet detected` modal, like this one?
Screenshot 2024-10-24 at 4 38 46 PM

- [ ] While we're at it, let's update the first sentence in that Sui modal to `No Sui wallet detected.`


- [ ] I tried to supply liquidity to make the new tokens easier to trade during testing, but ran into the [slippage issue](https://github.com/balancednetwork/balanced-network-interface/issues/1317) during the final supply transaction. This might be as good a time as any to implement the solution mentioned there?

**Comment by parrot9design** [comment]
Not sure if this is fully ready for me to start testing, but here's some initial feedback:

- [ ] Let's update the Solana blockchain logo to the variation I gave you previously ([solana-logos.zip](https://github.com/user-attachments/files/17741219/solana-logos.zip))
 Screenshot 2024-11-14 at 2 23 37 PM


- [ ] SOL doesn't appear in the token list, but it does in the variation on the Stats page?

- [ ] Noticing some issues with the loan. I tried to repay bnUSD on Solana, it took ages but once it took effect in the UI and my loan balance was reduced, I noticed I still had the full balance of bnUSD in my Solana wallet. Tried to borrow more just to see what would happen, that transaction has now been pending for longer than expected.
Screenshot 2024-11-14 at 3 51 51 PM Screenshot 2024-11-14 at 3 50 26 PM

**Comment by swiftcc624** [comment]
@parrot9design 

> SOL doesn't appear in the token list, but it does in the variation on the Stats page?

it's related to the backend api.

> Noticing some issues with the loan. I tried to repay bnUSD on Solana, it took ages but once it took effect in the UI and my loan balance was reduced, I noticed I still had the full balance of bnUSD in my Solana wallet. Tried to borrow more just to see what would happen, that transaction has now been pending for longer than expected. Here's the most recent one: https://xcallscan.xyz/messages/19663

I am still not clear what happened, I've just tested to deposit SOL, loan bnUSD and repay bnUSD, and it worked well. 
Can you please clear your local storage and test again?

**Comment by parrot9design** [comment]
>I am still not clear what happened, I've just tested to deposit SOL, loan bnUSD and repay bnUSD, and it worked well. Can you please clear your local storage and test again?

I started a new browser session, but I'm still having trouble repaying a loan with bnUSD on Solana. Xcallscan does not pick up any of my repay transactions.

The first time I tried repaying, I noticed this in the console logs (even after clearing local storage):

```
failed to check transaction hash: 214DpFfBtpi5b2b3yQFANWuUcFWnwjK71uMmpnTurwP5HV541JoiYPP1HbxRYqdZvgvQhfrGGL47KbVn1CU65dLW TypeError: Cannot read properties of undefined (reading 'getParsedTransaction')
    at SolanaXPublicClient.getTxReceipt (index-CJz3afum.js:1305:114159)
    at Object.queryFn (index-CJz3afum.js:2316:42705)
    at Object.To [as fn] (index-CJz3afum.js:41:75296)
    at qo (index-CJz3afum.js:41:70526)
    at createRetryer (index-CJz3afum.js:41:70981)
    at VR.fetch (index-CJz3afum.js:41:76053)
    at e6.Zx (index-CJz3afum.js:41:97856)
    at e6.onSubscribe (index-CJz3afum.js:41:92562)
    at e6.subscribe (index-CJz3afum.js:41:64552)
    at index-CJz3afum.js:41:104285
```

The second time I tried, I saw this:

```
[PHANTOM] Failed to send message to service worker. Retrying... Error: Attempting to use a disconnected port object
    at r (contentScript.js:13:5875)
r @ contentScript.js:13
(anonymous) @ solana.js:3
setTimeout
postMessage @ solana.js:3
send @ solana.js:3
#o @ solana.js:3
signAndSendTransaction @ solana.js:3
#d @ solana.js:3
sendTransaction @ index-CJz3afum.js:2276
await in sendTransaction
(anonymous) @ index-CJz3afum.js:2276
_executeRepay @ index-CJz3afum.js:1345
await in _executeRepay
executeTransaction @ index-CJz3afum.js:1345
sendXTransaction @ index-CJz3afum.js:4208
sendXTransaction @ index-CJz3afum.js:4208
J @ page-BK7hWV0d.js:169
Nb @ index-CJz3afum.js:38
Tb @ index-CJz3afum.js:38
Ub @ index-CJz3afum.js:38
nf$1 @ index-CJz3afum.js:38
se$2 @ index-CJz3afum.js:38
(anonymous) @ index-CJz3afum.js:38
Rk @ index-CJz3afum.js:41
Jb @ index-CJz3afum.js:38
hd @ index-CJz3afum.js:38
fd @ index-CJz3afum.js:38
ed @ index-CJz3afum.js:38
```

The third time I tried, there was no error (just the usual instances of `POST https://ctz.solidwallet.io/api/v3 400 (Bad Request)`), but again, nothing appears in xcallscan so these transactions aren't being registered at all.

---

Not sure why, but most Solana transactions I try caused xcallscan to load in multiple versions of the same transaction:
Screenshot 2024-11-18 at 9 18 41 AM

Screenshot 2024-11-18 at 9 37 46 AM

---

Also, I know we've talked about this before, but can we _please_ get the repay loan transactions to use the collateral chain for the destination instead of ICON? Solana users shouldn't need to know or care that ICON handles transactions in the background. And if you repay with bnUSD on a different chain, the transaction message isn't clear which loan you're actually repaying. At best seeing this will cause confusion, at worst, it's a cause for alarm.
Screenshot 2024-11-18 at 9 38 44 AM
Screenshot 2024-11-18 at 9 49 02 AM


---

Ran into a lot of issues with swaps from Solana, which weren't even registering in xcallscan:
Screenshot 2024-11-18 at 10 03 39 AM

This may be related to the amount of SOL I had in my wallet, as after I added some more xcallscan picked up the next swap I initiated from Solana, but it took more than 10 minutes to show as incomplete in the Balanced UI and on xcallscan. https://xcallscan.xyz/messages/20107
Screenshot 2024-11-18 at 10 13 55 AM


---

I also had trouble transferring bnUSD from Solana to other chains. In this case, they reverted.

https://xcallscan.xyz/messages/20113

---

Change JITOSOL to JitoSOL. 
Screenshot 2024-11-18 at 10 18 51 AM

**Comment by swiftcc624** [comment]
>Change JITOSOL to JitoSOL.

I fixed it.


@parrot9design for other things, Fez said that there is a problem with xcallscan, can we revisit this after it's resolved?

**Comment by parrot9design** [comment]
- [ ] Let's update this so the destination chain reflects the blockchain where the collateral is held, not ICON.
Screenshot 2024-11-20 at 10 42 10 AM

---

- [ ] Let's make sure to update all instances of JITOSOL in the UI, including in the modals and Bridge > Activity section. (Note: I've not yet tested any JitoSOL transactions)
Screenshot 2024-11-20 at 1 23 01 PM

---

I just finished another round of testing, here were some of the results:

Deposit sol collateral: 0:34
Withdraw sol collateral: 2:10
Borrow on solana: 2:04 / 1:59
Swap sui for sol: 2:04
Transfer bnUSD from solana to injective: 1:24
Transfer sol from icon to solana: 2:10

My initial repay transactions would either hang or fail. Then I managed to repay a solana loan with:
- Injective bnUSD in 0:29
- Solana bnUSD in 0:34

Now I'm back to being unable to repay bnUSD on Solana...

I also can't swap bnUSD on Solana for anything else. Nothing appears in xcallscan and the transactions remain pending in the UI. 

---

Also, this build includes Stellar. Do we need to wait for it to launch before we merge this PR?

**Comment by parrot9design** [comment]
I think some of the above issues (transactions pending in UI that aren't in xcallscan) may be due to the amount of SOL left in the wallet. Can you check that we have fallbacks in place for SOL? If not, is there a place we can add this as a to-do item for every new chain we implement?


Also, I just tried paying back my loan on Solana. It worked... kinda. The transaction went through, and the bnuSD left my wallet, but it still acts like my loan is near the maximum. The repayable indicator is about where I had tried to pay down to.
Screenshot 2024-11-20 at 1 44 39 PM

**Comment by FezBox** [comment]
- [ ] slider on loan wont go to 0
image

**Comment by parrot9design** [comment]
Here are the transaction times from my latest round of testing:

Depositing collateral: 0:40
Withdrawing collateral: 1:33
Borrowing bnUSD: 1:40
Repaying bnUSD: 0:40

Swapping XLM on ICON for SOL: 0:48
Swapping XLM on Stellar for SOL: 1:36

Transferring SOL from Solana to ICON: 1:05
Transferring bnUSD from Solana to Stellar: 1:18
Transferring bnUSD from Solana to Sui: 1:10
Transferring bnUSD from Solana to Base: 1:01
Transferring bnUSD from Solana to Injective: 1:01

If we're able to do anything to optimise the transaction speeds, it would be nice to get more of them under 1 minute. 

Otherwise, the main issues to address are related to repaying a loan:

- Address the blockchains mentioned in the Activity section
- Investigate why many repay transactions fail (my first one worked, but [2nd](https://xcallscan.xyz/messages/21138) and [3rd](https://xcallscan.xyz/messages/21139) attempts both failed)

**Comment by swiftcc624** [comment]
@parrot9design 

> Let's update this so the destination chain reflects the blockchain where the collateral is held, not ICON.

done


>If we're able to do anything to optimise the transaction speeds, it would be nice to get more of them under 1 minute.

nothing to do on the frontend, it's related to relayers and xcallscan.xyz.

**Comment by parrot9design** [comment]
During my last 7 attempts to repay bnUSD on Solana, only the 1st attempt succeeded. All the rest have failed. I have enough SOL in my wallet so I'm not sure what's causing this to be so reproducible?

https://github.com/user-attachments/assets/fcd343f2-823e-4c45-8f6b-f9365f252c91

**Comment by parrot9design** [comment]
JitoSOL has lost its updated formatting in most places:

Screenshot 2024-12-02 at 10 24 21 AM
Screenshot 2024-12-02 at 10 24 34 AM
Screenshot 2024-12-02 at 10 24 50 AM

As have the SUI LSTs:
Screenshot 2024-12-02 at 10 28 55 AM Screenshot 2024-12-02 at 10 29 14 AM
Screenshot 2024-12-02 at 10 29 20 AM Screenshot 2024-12-02 at 10 29 39 AM



If you choose JitoSOL from the `All collateral` tab, it defaults to Sui:

Screenshot 2024-12-02 at 10 27 56 AM

**Comment by swiftcc624** [comment]
@parrot9design I've fix formatting symbol, can you please check again?

**Comment by parrot9design** [comment]
> @parrot9design I've fixed formatting symbol, can you please check again?

Much better, thank you!

**Pull request merged**
