### PR TITLE
Feat/sui

### PR DESCRIPTION
**Pull request by swiftcc624**

### CODE REVIEW

**Comment by parrot9design** [comment]
- [ ] If you don't have a Sui wallet installed, nothing happens when you click `Connect wallet`. Related: https://github.com/balancednetwork/balanced-network-interface/issues/1429

- [ ] Hana doesn't appear to be supported yet? When I try to connect after enabling Sui in Hana, nothing happens, so that's about as far as I've gotten with testing so far.

**Comment by FezBox** [comment]
> * [ ]  If you don't have a Sui wallet installed, nothing happens when you click `Connect wallet`. Related: [Fix the 'Connect wallet' handling for ICON and EVM chains #1429](https://github.com/balancednetwork/balanced-network-interface/issues/1429)
> * [ ]  Hana doesn't appear to be supported yet? When I try to connect after enabling Sui in Hana, nothing happens, so that's about as far as I've gotten with testing so far.

hmm strange, after I disabled the sui wallet hana connected for me

**Comment by parrot9design** [comment]
>hmm strange, after I disabled the sui wallet hana connected for me

Weird. I have no other Sui wallets installed so that's not an issue here. I've only managed to get Hana to trigger for Sui's `Connect wallet` prompts after restarting my Mac or clearing data from the browser, but even then it only connects me to ICON or the EVM chains, never Sui.

This is what appears in the console logs:
Screenshot 2024-09-24 at 12 23 35 PM

---

- [ ] When you click `Choose address` for an asset on Sui, the modal appears with a broken-looking input field.

**How it looks for other chains** | **How it looks for Sui**
--------------------------------- | -------------------
Screenshot 2024-09-23 at 2 03 01 PM | Screenshot 2024-09-23 at 2 03 16 PM

- [ ] There's no address verification for Sui yet, as it currently accepts ICON and ETH addresses

---

- [ ] Let's use the same logo variation for the asset and chain. Here's an svg you can use for the chain:
[sui.svg.zip](https://github.com/user-attachments/files/17106192/sui.svg.zip)

**Comment by swiftcc624** [comment]
@parrot9design I've fixed all feedbacks, can you please check?

**Comment by parrot9design** [comment]
- [ ] Still noticing this issue for Sui, ICON, and EVM wallets:
>If you don't have a Sui wallet installed, nothing happens when you click Connect wallet. Related: https://github.com/balancednetwork/balanced-network-interface/issues/1429

---

- [ ] The default chain for the SUI token should be Sui, not ICON.

---

I was still having trouble connecting to Sui via Hana, turns out this was the problem: https://support.hanawallet.io/en/articles/9827255-why-can-t-i-generate-certain-blockchain-addresses-in-my-hana-wallet

---

Regarding transaction speeds, the majority of the swaps/transfers I tested included a delay between when the destination wallet balance updated and the modal/activity section treated the transaction as complete.

- Swaps/transfers between ICON and Sui: 17-30 seconds to update the balance. At least another 15-30+ seconds to finalise in activity section.
- Transferring bnUSD from Sui to Injective: 26 seconds to update the balance, 1m 15s to finalise in activity section
- Transferring bnUSD from Sui to Base: over 2 minutes. No delay between balance & activity section
- Swapping between ICON & Base: 42 seconds to update the balance. Activity section updated 5 seconds later
- Swapping between Injective & Arbitrum: 1m 25s. unsure if there was a delay between balance & activity section
- Swapping from Arbitrum to Sui: 26 seconds to update the balance, 1 minute to finalise in activity section
- swapping from Sui to Archway: 38 seconds to update the balance, 1 minute to finalise in activity section
- Swapping from Arbitrum to BNB Chain: 35 seconds to update the balance, 53 seconds to finalise in activity section

Comparison to the live app:

- Swapping from Base to Avalanche: 38 seconds for the balance, another ~8 seconds to finalise in activity section
- Swapping from ICON to Base: 1 minute for the balance, another ~8 seconds to finalise in activity section
- Swapping from Injective to Arbitrum: ~30 seconds
- Swapping from ICON to Avalanche: 29 seconds for the balance, another ~6 seconds to finalise in activity section
- Transferring from Avalanche to Archway: ~34 seconds for the balance, another 4 seconds to finalise in activity section
- Transferring from Archway to Havah: 45 seconds for the balance, another 30+ seconds to finalise in activity section

**Comment by parrot9design** [comment]
- [ ] When I click Deposit in the confirmation modal for SUI collateral, nothing happens. I get this error in the console:

Screenshot 2024-10-01 at 5 31 14 PM

---

- [ ] I frequently have issues using ETH on Arbitrum (for collateral/swaps/transfers) unless I use a minuscule amount, even when I leave more than enough to account for fees:
Screenshot 2024-10-01 at 5 39 59 PM
Screenshot 2024-10-01 at 5 38 41 PM


---

- [ ] The borrow fee resets to 0 once a transaction is in progress:
Screenshot 2024-10-01 at 5 52 25 PM

---

- [ ] My Sui bnUSD balance doesn't appear in the Loan blockchain selector:

Screenshot 2024-10-01 at 5 55 15 PM Screenshot 2024-10-01 at 5 55 23 PM

---

Also worth noting: all but two transactions I tested today took 1m15s – 1m30s to complete.

**Comment by swiftcc624** [comment]
@parrot9design I've fixed issues regarding collateral and loans. Can you please check them?

**Comment by parrot9design** [comment]
Thanks! I managed to deposit SUI collateral and borrow bnUSD on Sui this time. It took around 1-1.5 minutes for the modal to say it was successful, but the Collateral/Loan sections won't update with the new values unless you leave the page and come back again.

Can you please resolve this plus the other comments mentioned in my previous comment before my next review?

**Comment by swiftcc624** [comment]
@parrot9design 

> I frequently have issues using ETH on Arbitrum (for collateral/swaps/transfers) unless I use a minuscule amount, even when I leave more than enough to account for fees:

> The borrow fee resets to 0 once a transaction is in progress:


Do you still get those issue? Did you get them in the just previous testing?

**Comment by swiftcc624** [comment]
image

>If you don't have a Sui wallet installed, nothing happens when you click Connect wallet. Related: https://github.com/balancednetwork/balanced-network-interface/issues/1429

It shows the modal in the screenshot in that case on my side.

**Comment by parrot9design** [comment]
Strange, I can't get the ICON, EVM, or Sui `Connect wallet` prompts to trigger in any browser on Mac or iOS unless there's a compatible wallet installed.

Let's update that Sui message to:

>No Sui-based wallet detected.
>
>Add a wallet like [Hana]() or [Sui Wallet]() to your browser, then try again.

---

>Do you still get those issues? Did you get them in the just previous testing?

I encounter these issues in both this build and the live app, but as Balanced development has been neglected in favour of HanaSwap recently, let's at least get the Arbitrum issue fixed now to avoid waiting weeks for the fix.

**Comment by parrot9design** [comment]
- [ ] If you click to connect an ICON wallet without one installed, nothing happens. It should direct you to the Hana Chrome Store listing, similar to the Archway and Havah wallets.

---

- [ ] Why am I seeing `Confirming the transaction on ICON...` messages for transactions that don't directly involve the ICON blockchain? People shouldn't be exposed to ICON unless they choose to transact with it.
**This is a regression from the live app.**
Screenshot 2024-10-07 at 1 18 39 PM

It should be:
>Confirming transaction on {origination chain}...

>Finalising transaction on {destination chain}...

---

- [ ] It still takes a loooong time for most Sui transactions to finalise.
Screenshot 2024-10-07 at 2 21 21 PM
Sometimes one will revert when I start a new transaction, but the rest are in no hurry to resolve themselves.

---

- [ ] I'm unable to repay my loan using bnUSD on Sui. Nothing happens when I click Repay in the confirmation modal.
I assume this is because, even though the Loan section itself realises I have a bnUSD balance on Sui (no `Repayable` indicator appears on the bar), my Sui bnUSD balance still appears as 0 in the blockchain selector.
Screenshot 2024-10-07 at 1 30 11 PM Screenshot 2024-10-07 at 1 30 18 PM

**Comment by swiftcc624** [comment]
@parrot9design I've fixed all feedbacks except ` It still takes a loooong time for most Sui transactions to finalise.`

But it's not my scope and it's fixed, I think.

Can you please check the latest build again?

**Comment by parrot9design** [comment]
- [ ] I'm still seeing ICON mentioned in a few of the transaction messages.
Screenshot 2024-10-08 at 9 37 29 AMScreenshot 2024-10-08 at 9 35 44 AM

- [ ] The bnUSD balance on Sui still isn't being pulled through in the loan blockchain selector
Screenshot 2024-10-08 at 9 37 48 AM

**Comment by parrot9design** [comment]
- [ ] Let's also update the default swap pair: SUI on Sui for ETH on Base

**Comment by swiftcc624** [comment]
image

> I'm still seeing ICON mentioned in a few of the transaction messages.

@parrot9design it's because the destination chain of Repay is ICON

you said
```
It should be:

Confirming transaction on {origination chain}...

Finalising transaction on {destination chain}...
```

**Comment by swiftcc624** [comment]
>The bnUSD balance on Sui still isn't being pulled through in the loan blockchain selector

>Let's also update the default swap pair: SUI on Sui for ETH on Base

@parrot9design I've fixed the above feedbacks.

**Comment by parrot9design** [comment]
> > I'm still seeing ICON mentioned in a few of the transaction messages.
> 
> @parrot9design it's because the destination chain of Repay is ICON
> 
> you said
> 
> ```
> It should be:
> 
> Confirming transaction on {origination chain}...
> 
> Finalising transaction on {destination chain}...
> ```

I meant the destination chain from the **user's** perspective. If they haven't chosen to interact with ICON, they shouldn't need to know about it. Here, the destination chain would be Sui because that's the chain my collateral position is held on:
Screenshot 2024-10-08 at 6 34 22 PM


So the logic would be:
Deposit/withdraw collateral: confirm and finalise on the collateral chain (e.g. Sui for SUI collateral)
Borrow bnUSD: confirm on the collateral chain, finalise on the active chain in the Loan section
Repay bnUSD: confirm on the active chain in the Loan section, finalise on the collateral chain


---

- [ ] I'm now seeing an `Approve transfer` button in all Sui-related confirmation modals, none of which trigger the wallet (Hana), so I can't test any Sui transactions right now:

Screenshot 2024-10-08 at 6 35 43 PM
Screenshot 2024-10-08 at 6 36 12 PM
Screenshot 2024-10-08 at 6 36 27 PM
Screenshot 2024-10-08 at 6 36 41 PM
Screenshot 2024-10-08 at 6 40 35 PM

**Comment by swiftcc624** [comment]
>I'm still seeing ICON mentioned in a few of the transaction messages.

> I'm now seeing an Approve transfer button in all Sui-related confirmation modals, none of which trigger the wallet (Hana), so I can't test any Sui transactions right now:


@parrot9design I've fixed them, can you please check again?

**Comment by parrot9design** [comment]
Looks good, thank you!

I found another issue that I initially thought was due to the Sui relay, but turned out to be because of gas. If your SUI balance is below a certain level, you're still able to confirm transactions, but they never appear in xcallscan so they remain in a pending state until they revert (which is only triggered by starting another transaction). Even if I choose to use the max SUI (which leaves 0.02 in my wallet), the transaction won't succeed.

Can you please add handling for SUI to prevent people from proceeding if they don't have enough gas to complete the transaction, similar to how we've done for gas on other chains?

**Comment by swiftcc624** [comment]
@parrot9design I fixed gas checking, can you please check again?

**Comment by parrot9design** [comment]
It still doesn't check for gas. Whether I use the 100% input option or enter an amount manually, it continues to act like the transaction will go through as normal.

Only Avalanche and BNB Chain appear to check gas properly at the moment.

**Comment by swiftcc624** [comment]
@parrot9design I've fixed it, can you please check it again?

**Comment by parrot9design** [comment]
I withdrew SUI collateral, which appeared to work well from the xcallscan side, but it's still pending in the UI 7+ minutes later. 

Also need to fix up this decimal issue in the collateral dropdown
Screenshot 2024-10-10 at 9 54 14 AM

**Comment by swiftcc624** [comment]
@parrot9design is it still pending? can you please double click it and give me the xcallscan link?

**Comment by parrot9design** [comment]
I quit out of the browser so it no longer appears under Bridge > Activity, but my SUI is still being held as collateral.

I think this was my first transaction: https://xcallscan.xyz/messages/17116
And here's one I just started. It executed on xcallscan almost instantly, but gets stuck finalising on the frontend. https://xcallscan.xyz/messages/17126

Fez mentioned he also encountered the same problem.

**Comment by swiftcc624** [comment]
@parrot9design it's because you didn't replay the full/exact bnUSD amount. You need to borrow some and repay full amount again. And then you can withdraw all SUI.

**Comment by parrot9design** [comment]
Oh weird, yeah that fixed it – thanks!

The UI never had any indication that there was any loan remaining, and I repaid it right before I tried to withdraw collateral. Will this affect any new users, or only those who borrowed before you updated the decimal issue?

**Comment by swiftcc624** [comment]
@parrot9design 

> Will this affect any new users, or only those who borrowed before you updated the decimal issue?

only those who borrowed before you updated the decimal issue?

**Comment by parrot9design** [comment]
Ok nice, thanks.

One issue that's just burned me a couple of times: If I deposit max SUI, it doesn't leave me with enough SUI to complete any other transactions. I can't borrow bnUSD or even withdraw my collateral without trying to find a way to top up my wallet.

This doesn't seem to be an issue for others, e.g. I can deposit and then withdraw ETH on Base without needing to worry about how to pay for the gas.

**Comment by swiftcc624** [comment]
@parrot9design Did you get the issue on the latest build?

**Comment by parrot9design** [comment]
Yes, I always use the latest build.

**Comment by swiftcc624** [comment]
@parrot9design I've fixed it, can you please check again?

**Comment by parrot9design** [comment]
After depositing max SUI as collateral, I'm able to sign other transactions, e.g. repay bnUSD and swap, but the transaction never appears in xcallscan and it reverts as soon as I start another one.

I also noticed the cross-chain fee for Sui has been updated – is it supposed to be 0.11 SUI? It was more like 0.000000011 SUI earlier.

**Comment by swiftcc624** [comment]
@parrot9design 

> is it supposed to be 0.11 SUI? 

Yes

> it was more like 0.000000011 SUI earlier.

It was wrong before, Sui decimals 9, it was treated as 18 decimals before.


> After depositing max SUI as collateral, I'm able to sign other transactions, e.g. repay bnUSD and swap, but the transaction never appears in xcallscan and it reverts as soon as I start another one.

Can you please give me the detailed steps? So I can reproduce it on my side.

**Comment by swiftcc624** [comment]
>After depositing max SUI as collateral, I'm able to sign other transactions, e.g. repay bnUSD and swap, but the transaction never appears in xcallscan and it reverts as soon as I start another one.

@parrot9design I increased gasThreshold, can you please test again?

**Comment by parrot9design** [comment]
Yeah, that's much better. This should be good to ship. 💪

**Pull request merged**
