### PR TITLE
Add tBTC cbBTC weETH wstETH tokens

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by parrot9design** [comment]
- [ ] I keep getting a "transfer failed" message when I try to deposit weETH on Arbitrum.

- [ ] It's not detecting the cbBTC in my wallet:
Screenshot 2024-09-25 at 6 28 26 PM


- [ ] Can we hide assets in the `Your assets` list if you have less than $1 of liquidity?
Screenshot 2024-09-25 at 6 32 45 PM

- [ ] When I try to deposit tBTC, I get this error in Hana:
Screenshot 2024-09-25 at 6 34 24 PM

**Comment by hetfly** [comment]
@parrot9design tBTC works fine for me, could check it out again please? I could bridge and deposit collateral from both networks.

weETH and cbBTC need to be fixed through governance vote. Do we want wait and release it in batch or split it and release tBTC and wstETH now?

**Comment by parrot9design** [comment]
>tBTC works fine for me, could check it out again please? I could bridge and deposit collateral from both networks.

Originally encountered the same issue, but it resolved itself once I increased my ETH balance from $5 to $15.

>weETH and cbBTC need to be fixed through governance vote. Do we want wait and release it in batch or split it and release tBTC and wstETH now?

Will that fix get added to next week's proposal, or would we do it sooner? I wasn't expecting their addition to cause an immediate uptick, so unless anyone has an objection I'm tempted to wait and release them in a batch.

**Comment by FezBox** [comment]
Whatever is the quickest.
Also keeping @AntonAndell in the loop

I haven't really understood what the issue is

**Pull request merged**
