### PR TITLE
Feat/implement staking LP token

### PR DESCRIPTION
**Pull request by Chunn**

### CODE REVIEW

**Comment by parrot9design** [comment]
If there's no BALN to incentivise a pool, we should remove the `%` symbol and just use an en-dash `–` to keep it tidy. `-%` is just awful and we should strive to never show data like that in the UI.

**Current** | **Preferred**
----------- | -------------
Screen Shot 2021-11-15 at 5 08 26 PM | Screen Shot 2021-11-15 at 5 11 10 PM
 
I can't actually text anything beyond that, as the UI isn't picking up the assets in my wallet on Sejong. Anyone else been having that issue recently, or is it just me?

**Comment by Chunn** [comment]
> If there's no BALN to incentivise a pool, we should remove the `%` symbol and just use an en-dash `–` to keep it tidy. `-%` is just awful and we should strive to never show data like that in the UI.
> 
> **Current**	**Preferred**
> Screen Shot 2021-11-15 at 5 08 26 PM	Screen Shot 2021-11-15 at 5 11 10 PM
> I can't actually text anything beyond that, as the UI isn't picking up the assets in my wallet on Sejong. Anyone else been having that issue recently, or is it just me?

@parrot9design Currently, we use the Yeouido addresses that are Galen deployed to test this feature. Please check on Yeouido. Thank you!

- Also, I've resolved to remove the % symbol. However, seems to the current address set does not show APY.
- Regarding staking LP token, It seems we can only check `sICX / bnUSD` .

FYI: https://iconcommunity.slack.com/archives/G0117R69JK0/p1636464135148000

**Comment by octocat512** [comment]
I briefly saw your code. Why did you disable some eslint rules? Please remove the comments.

**Comment by BennyOptions** [comment]
"BALN-incentivised pools

[Slider should work the same as in the Collateral and Loan sections: when you click Adjust, the slider appears along with the Cancel and Confirm buttons.
As you move the slider, the Daily rewards and Available values should also change (Available = unstaked supply balance)"

@Chunn, the "Daily Rewards" sections should be 0 if I have not staked LP tokens. These numbers should increase and decrease as the user adjusts the slider for how many LP tokens they will stake. Right now, I have 0 LP tokens staked, so the number should be 0. As I adjust how many are staked, this number should also adjust.

Screen Shot 2021-11-16 at 1 46 22 AM

**Comment by BennyOptions** [comment]
After staking LP tokens, the entire "liquidity details" section disappears. The UI must recognize that the user has staked LP tokens. To be clear:

If the user has 0 staked LP and 0 liquidity -> "Liquidity Details" does not appear

else -> "liquidity details" must appear

Screen Shot 2021-11-16 at 1 51 39 AM

**Comment by BennyOptions** [comment]
Two issues:

- The bar is full, but it should not be full because I have 27.69 LP tokens available to stake
- It should be number of LP tokens in wallet / number of LP tokens in wallet + number of staked LP tokens. Right now, it is backwards.

Screen Shot 2021-11-16 at 1 55 33 AM

**Comment by BennyOptions** [comment]
Selecting the BALN/bnUSD pool to supply liquidity crashes the app.

Address testing: hxdf7c371a35b4acb19d9f869a68eed8721503eaea


https://user-images.githubusercontent.com/43685868/142750245-74333f83-3ddf-4523-b9b1-16a6d34f81a4.mov

**Comment by BennyOptions** [comment]
All logos disappeared in the drop down

Screen Shot 2021-11-21 at 12 03 28 AM

**Comment by BennyOptions** [comment]
There are many things wrong with this build. I am not sure, but I feel there must be a deeper problem than these individual issues.

I can't trade ICX for sICX.

Transaction: https://bicon.tracker.solidwallet.io/transaction/0x9635c97e9c36e679e31cfc13aa946bdbd3ac90a92484c43bdafa085356534fb3


https://user-images.githubusercontent.com/43685868/142750354-f9b9ffa0-f88a-41dd-aad8-94eca0ef8cfc.mov

**Comment by parrot9design** [comment]
Background colour for the asset fields under Withdraw should be `rgb(12, 42, 77)`. It's currently `rgb(2, 19, 56)`. Assuming you know the icons are missing. 
Screen Shot 2021-11-22 at 2 24 01 PM

---
Screen Shot 2021-11-22 at 2 21 38 PM

- Replace `Wallet` with `Available`, and make the amounts update as you move the slider.
   - **Nothing staked.** Total supply balance is available to withdraw
   - **Fully staked.** Nothing is available to withdraw


---

`Tokens` in the top line should be lowercase (`tokens`)
Screen Shot 2021-11-22 at 2 33 01 PM Screen Shot 2021-11-22 at 2 34 04 PM

---

The `x LP tokens` piece should be white as well as bold to give it more contrast.
Current:

Preferred:

**Comment by BennyOptions** [comment]
Two issues I found so far:

- [ ] The numbers update very slowly when using the slider, it is choppy, not smooth. It is smooth for the "withdraw" section, but choppy on the "Stake LP Tokens" section
- [ ] The Liquidity Details section disappears when I supply 100% of my LP tokens


https://user-images.githubusercontent.com/43685868/142797533-12b82f61-699c-4204-8a3e-1046dc171a35.mov

**Comment by BennyOptions** [comment]
The "Rewards" panel has an issue - it always takes two transactions to claim rewards. I have tested this many times, and it happens every time I claim. However, both transactions appear to go through.

@gedanziger is this a contract issue or a frontend issue? It appears to be contract side looking at the transactions

Tx1 (no rewards actually claimed): https://bicon.tracker.solidwallet.io/transaction/0x797e03405c1747336bf76eab4008b376a8e014bf878ac491bb6638be8e3ac12b#events

Tx2 (rewards will claim properly): https://bicon.tracker.solidwallet.io/transaction/0xcfe486d76284cbae08c219600fd4104e42ad1544eb02ea2cbe6355d14c74d9fb#internaltransactions




https://user-images.githubusercontent.com/43685868/142797841-3dad9565-9062-43c8-b372-7f0ac0ec89c2.mov

**Comment by parrot9design** [comment]
> The Liquidity Details section disappears when I supply 100% of my LP tokens

Seems to be defaulting to the same behaviour as third-party pools like OMM/sICX and CFT/sICX, where it's expected that staking 100% of your LP tokens removes it from the Balanced UI.

**Comment by BennyOptions** [comment]
- [ ] Pool Share should not change with staking LP tokens. Pool share is the same if you stake or not.
- [ ] Daily rewards disappears if you have 100% LP tokens staked, then start to remove some


https://user-images.githubusercontent.com/43685868/143800518-5ce183ad-9bdf-4e7c-a18f-e9fd934e859f.mov

**Comment by BennyOptions** [comment]
Here is a better video of the Pool Share issue from my previous comment


https://user-images.githubusercontent.com/43685868/143801120-f37e5331-9a5e-4cef-88e0-1a029b1b3c81.mov

**Comment by BennyOptions** [comment]
UI showing 0 BALN available to claim but should be much higher. Also, blockchain does not seem to give the correct rewards @gedanziger 

Transaction: https://sejong.tracker.solidwallet.io/transaction/0x55c2a28f51ac96d8303df057e88395686155b80729a50c9f7ea8a8fc34d231b8

https://user-images.githubusercontent.com/43685868/143802160-1742664e-53cc-4ad2-a8d4-0da7a9a89955.mov

**Comment by parrot9design** [comment]
- [ ] When you adjust the LP staking slider, the `Available` balance should change to show how much the user has available to withdraw. It's still static in the latest version
- [ ] When you use the slider to withdraw liquidity, the `Your supply` and `Pool share` values should also change

- [ ] The tickers next to the `Withdraw` heading should use `font-weight: normal` and `font-size: 16px`:

**Current** | **Design**
----------- | ----------
Screen Shot 2021-11-30 at 2 54 49 PM | Screen Shot 2021-11-30 at 2 54 44 PM

----

- [ ] Now that we've gotten rid of the content in the supply liquidity section, let's address the sizing. There's way too much empty space at the bottom of the panel, so we should get it as close to what we have in the [prototype](http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/) as possible, which has only 35px of space underneath the `Supply` button:

**Current** | **Design**
----------- | ----------
Screen Shot 2021-11-30 at 3 15 20 PM | Screen Shot 2021-11-30 at 3 08 56 PM
Screen Shot 2021-11-30 at 3 15 26 PM | 

---

- [ ] For the `Your daily rewards` value, @BennyOptions what are your thoughts on rewording that to `Your potential rewards`? 
Screen Shot 2021-11-30 at 3 24 57 PM

- It allows us to show people what they _could_ be earning, vs what they're _actually_ earning, which they see in the liquidity details section
- If it's fully dependent on the amount of LP tokens staked, as previously suggested, there's no value keeping it in the top section at all, as it'd always be irrelevant to the task of supplying liquidity, especially when it's `0` because no LP tokens have been staked.

**Comment by BennyOptions** [comment]
Claim does not work


https://user-images.githubusercontent.com/43685868/144179110-0aa6b58b-01ae-4e69-a1ad-c0b22901b04b.mov

**Comment by BennyOptions** [comment]
If I unstake my LP tokens then claim all my BALN, the "Rewards" section goes to "pending" and does not come back, even though I am earning BALN from my Loan. It should show me the amount I can claim from my Loan.

https://user-images.githubusercontent.com/43685868/144187691-19350f8b-896f-48a4-9cb5-f387123bc6c6.mov

**Comment by BennyOptions** [comment]
Also, there should never be a "pending" state with continuous rewards. You can remove this text. It is either 0 or above 0

**Comment by parrot9design** [comment]
- [ ] When you use the slider to withdraw liquidity, the `Your supply` and `Pool share` values should also change:
Screen Shot 2021-12-09 at 4 53 40 PM


- [ ] Change the `Your daily rewards` label to `Your potential rewards`:
143974901-6423043a-50e9-481c-8272-2d7a1dca3df4

- [ ] For the ICX confirmation modal, update the value to an h3 (font-size:20px):
Screen Shot 2021-12-09 at 4 58 44 PM

- [ ] Often after supplying liquidity (tested mostly with the sICX/ICX pool), the supply values in the top left section don't reset to 0, so if you're trying to compare your supply or potential rewards to the liquidity details section, the values won't match.
Screen Shot 2021-12-09 at 5 02 55 PM

- [ ] Kept running into an `invalid parameter` issue when trying to supply sICX to the sICX/bnUSD pool: https://sejong.tracker.solidwallet.io/transaction/0x102f587fd1a7de541195b30bc479af66ad58e16d16d28d62d59f5db9c9a09b5f

**Comment by parrot9design** [comment]
Also, if this will be merged after https://github.com/balancednetwork/balanced-network-interface/pull/807, is it possible to set a trigger so that when you expand a pool in the liquidity details section, the supply liquidity section displays the details for that pool, as well? The custom LP changes make the pool selection process less direct, so having an easy way to access & add to the pools you're already in would enhance that experience.

**Comment by BennyOptions** [comment]
@rise-techiast @Chunn 

The trade page crashes in this PR

**Comment by BennyOptions** [comment]
Selecting "ICX" in the "Supply Liquidity" section breaks the app if you are logged in


https://user-images.githubusercontent.com/43685868/151715470-03390af5-d9e3-4f46-a86b-9a1725fe91c2.mov

**Comment by octocat512** [comment]
Please resolve conflicts. @Chunn

**Comment by BennyOptions** [comment]
Let's resolve conflicts and clean up this code after sICX integration to Defi Llama @shallcdn

**Comment by BennyOptions** [comment]
Implement #949 on this PR as well

**Comment by BennyOptions** [comment]
@octocat512 please implement #981 on this PR.

**Comment by BennyOptions** [comment]
@rise-techiast please have some members resolve the conflicts

**Comment by shallcdn** [comment]
Demo for staking LP
https://user-images.githubusercontent.com/99955678/172433489-14e39591-ff74-4933-8467-efaff8818279.mp4

**Comment by parrot9design** [comment]
If you haven't supplied liquidity, and aren't in the process of it, the rewards should say `N/A` instead of `~ 0.0000 BALN`:
Screen Shot 2022-06-10 at 10 24 13 AM

- Let's also keep the BALN number to 2 decimal places. 4 is a bit excessive.

---

ICX is missing the slider. It should be the same as in the app currently:

**This PR** | **App**
----------- | ----------
Screen Shot 2022-06-10 at 10 25 24 AM | Screen Shot 2022-06-10 at 10 25 32 AM

---

As you drag the slider to set the amount to supply, the `Your supply` and `Your daily rewards` numbers should adjust to reflect the amount, just as they do for the LP staking slider. If they don't adjust while you're choosing the amount, there's no point highlighting them in the top section at all.

**Comment by BennyOptions** [comment]
@rise-techiast @shallcdn this is high priority. Staking LP tokens via smart contract will be ready in 2 days, this should also be ready ideally.

**Comment by parrot9design** [comment]
> Hi @parrot9design
> 
> > As you drag the slider to set the amount to supply, the Your supply and Your daily rewards numbers should adjust to reflect the amount, just as they do for the LP staking slider. If they don't adjust while you're choosing the amount, there's no point highlighting them in the top section at all.
> 
> I think only the Your supply should adjust to reflect the amount.
> 
> If we drag the slider, the Your daily rewards also change and then the user performs to provide liquidity; this field will be reset to 0 or N/A, or the old reward value that the user has before, which confuses the user. Because the user still hasn't been staked LP token, the user isn't rewarded
> 
> What do you think about this case?

@shallcdn I'm not sure why this change was reversed, but previously (see https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-989492278 and https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-982222483) we changed `Your daily rewards` to `Your potential rewards` so that it's easy for people to see what they could earn by supplying a certain amount to the pool before completing the transaction. This is also helpful for existing LPs to compare against the rewards shown in the liquidity details section, especially if they've only partially staked their LP tokens.

**Comment by shallcdn** [comment]
> > Hi @parrot9design
> > > As you drag the slider to set the amount to supply, the Your supply and Your daily rewards numbers should adjust to reflect the amount, just as they do for the LP staking slider. If they don't adjust while you're choosing the amount, there's no point highlighting them in the top section at all.
> > 
> > 
> > I think only the Your supply should adjust to reflect the amount.
> > If we drag the slider, the Your daily rewards also change and then the user performs to provide liquidity; this field will be reset to 0 or N/A, or the old reward value that the user has before, which confuses the user. Because the user still hasn't been staked LP token, the user isn't rewarded
> > What do you think about this case?
> 
> @shallcdn I'm not sure why this change was reversed, but previously (see [#770 (comment)](https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-989492278) and [#770 (comment)](https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-982222483)) we changed `Your daily rewards` to `Your potential rewards` so that it's easy for people to see what they could earn by supplying a certain amount to the pool before completing the transaction. This is also helpful for existing LPs to compare against the rewards shown in the liquidity details section, especially if they've only partially staked their LP tokens.

Because we have three kinds of liquidity pools:
1. ICX/sICX => user supplies liquidity and receives daily rewards
2. The pair BALN/bnUSD and some pairs we support for stake LP => user supplies liquidity, then perform stake LP tokens   and receives daily rewards
3. The pair BALN/sICX and some pairs we don't support for stake LP => user supplies and move to other platforms to stake LP token and earn reward

My question for case 2, If we adjust the slider to set the amount to supply, `Your supply` also change is ok, but with `Your daily rewards` change, after the user has supplied, we should revert to the previous value because this value change based on the supply amount value just estimation daily reward not real daily reward => to received real daily reward user must perform one more step that stakes lp tokens. 

And when we revert to the previous value that makes the user confused, where is him/her daily reward?

**Comment by parrot9design** [comment]
For case 1, the slider should adjust the values for `Your supply` and `Your daily rewards` without any reason for confusion.

For case 2, the slider should also adjust the values for both, but the label should be `Your potential rewards` instead of `Your daily rewards`. Whether they've staked their LP tokens or not is irrelevant as it's an estimation (hence _potential_ rewards) – they can compare their potential/estimated rewards against their actual rewards shown in the liquidity details section. Because it's an estimation, the amount displayed before/after they complete the transaction won't need to change to reflect real rewards. If we weren't to update this value at all during the supply liquidity flow, it's honestly pointless displaying it to users at all.

For case 3, I'm assuming BALN/sICX wasn't a good example as it _is_ an incentivised pool? But unincentivised pools won't show the daily rewards row at all, as there's no BALN to be earned.

**Comment by shallcdn** [comment]
> For case 1, the slider should adjust the values for `Your supply` and `Your daily rewards` without any reason for confusion.
> 
> For case 2, the slider should also adjust the values for both, but the label should be `Your potential rewards` instead of `Your daily rewards`. Whether they've staked their LP tokens or not is irrelevant as it's an estimation (hence _potential_ rewards) – they can compare their potential/estimated rewards against their actual rewards shown in the liquidity details section. Because it's an estimation, the amount displayed before/after they complete the transaction won't need to change to reflect real rewards. If we weren't to update this value at all during the supply liquidity flow, it's honestly pointless displaying it to users at all.
> 
> For case 3, I'm assuming BALN/sICX wasn't a good example as it _is_ an incentivised pool? But unincentivised pools won't show the daily rewards row at all, as there's no BALN to be earned.

I take your point; let me update like this, thanks

**Comment by octocat512** [comment]
@shallcdn please resolve conflicts.

**Comment by shallcdn** [comment]
> @shallcdn please resolve conflicts.

Yes sure, Chunn is working to update this PR please wait.

**Comment by BennyOptions** [comment]
Right now, the page takes a very long time to load. Can this be made more efficient @rise-techiast @shallcdn @octocat512 ?


https://user-images.githubusercontent.com/43685868/175457954-984f154e-1735-450a-a7fc-8f536d1c0424.mov

**Comment by parrot9design** [comment]
I have 0 BALN in this wallet, yet I can still use the slider, and it tells me that the _bnUSD_ balance is insufficient:
Screen Shot 2022-06-24 at 4 13 49 PM Screen Shot 2022-06-24 at 4 14 00 PM

Here's how it looks in production:
Screen Shot 2022-06-24 at 4 16 29 PM Screen Shot 2022-06-24 at 4 16 36 PM


I'm actually getting the "Insufficient bnUSD balance" for other pools, as well, even though I have enough in my wallet: 
Screen Shot 2022-06-24 at 4 20 00 PM Screen Shot 2022-06-24 at 4 23 40 PM Screen Shot 2022-06-24 at 4 27 10 PM

**Comment by shallcdn** [comment]
Hi @parrot9design
> I'm actually getting the "Insufficient bnUSD balance" for other pools, as well, even though I have enough in my wallet:
You see `Insufficient bnUSD balance` because each pool has a minimum for quote token, if you provide an amount of quote token doesn't greater than the value you will see it  "Insufficient <quote_token> balance".

**Comment by parrot9design** [comment]
> You see `Insufficient bnUSD balance` because each pool has a minimum for quote token, if you provide an amount of quote token doesn't greater than the value you will see it "Insufficient <quote_token> balance".

Is that a new thing? I don't encounter the same issue when using the same wallet with the production version.

**Comment by BennyOptions** [comment]
@shallcdn I believe you can remove the logic for insufficient quote token. That is removed with continuous rewards.

**Comment by shallcdn** [comment]
> > You see `Insufficient bnUSD balance` because each pool has a minimum for quote token, if you provide an amount of quote token doesn't greater than the value you will see it "Insufficient <quote_token> balance".
> 
> Is that a new thing? I don't encounter the same issue when using the same wallet with the production version.

Yes, that is a new thing, if we don't supply an amount quote token greater than the minimum value the transaction will be failed.

**Comment by BennyOptions** [comment]
Ok, @shallcdn I asked smart contract guys and the smart contract still has this requirement. @parrot9design  In production, the UI does not check for it. User will submit transaction and it will fail. Now the UI catches it, it seems

**Comment by parrot9design** [comment]
@shallcdn Instead of showing "Insufficient <quote_token> balance" in the button, we could handle this with a tooltip as we did previously – see https://github.com/balancednetwork/balanced-network-interface/pull/503 for more info.

**Comment by BennyOptions** [comment]
@shallcdn please change it back to main net

**Comment by parrot9design** [comment]
After successfully staking LP tokens, the UI didn't change. It continued to show that I had no LP tokens staked until I either went to another page and came back again, or moved between the Swap/Supply liquidity tabs.
Screen Shot 2022-06-25 at 12 52 18 PM

The same thing happened after unstaking them, so I tried to unstake again to see what would happen:
Screen Shot 2022-06-25 at 12 56 01 PM

---

Instead of keeping the `Insufficient bnUSD balance` button and using `10.00 minimum` for the tooltip, as shown here:
Screen Shot 2022-06-25 at 1 00 12 PM

Let's make the button say `Supply` and the tooltip `10 {ticker} minimum` (10 bnUSD minimum, in this case), whic is how it worked previously:
Screen Shot 2022-06-25 at 1 00 42 PM

---
The tooltip is messing with the UI at smaller screen sizes:
Screen Shot 2022-06-25 at 1 03 22 PMScreen Shot 2022-06-25 at 1 04 54 PM

Or isn't visible at all:
Screen Shot 2022-06-25 at 1 04 18 PM

When it can't fit cleanly in view, let's float it underneath, like it does here (see https://github.com/balancednetwork/balanced-network-interface/pull/503#issuecomment-881466908):
125958704-32b4e38f-4c66-4f7a-a09f-7a1381833c8d

---

After staking LP tokens for the sICX/bnUSD pool, I went to the Home page to check the rewards section, but it still shows that I'm ineligible for Balance Token rewards?
Screen Shot 2022-06-25 at 1 11 21 PM

---

We had a banner message prepared to make sure people were aware of the change. Can we make sure this message is enabled when we merge to production? https://github.com/balancednetwork/balanced-network-interface/pull/891

**Comment by shallcdn** [comment]
Hi @parrot9design I have fixed your comments; please help take a look

**Comment by BennyOptions** [comment]
LP tokens for IUSDC/bnUSD seem to be off. This wallet has a large percentage of the pool but only displays 0.16 LP tokens @shallcdn

**Comment by BennyOptions** [comment]
Pools that this wallet previously contributed to, but has no currently LP tokens is still displayed in the UI. It should not be displayed

Screen Shot 2022-06-25 at 2 11 57 AM
Screen Shot 2022-06-25 at 2 11 47 AM

**Comment by BennyOptions** [comment]
The tooltip should only appear if the user does not have any liquidity in the pool. If a user is currently an LP (like in this image), then they can contribute any amount of liquidity. 

Screen Shot 2022-06-25 at 2 16 06 AM

**Comment by BennyOptions** [comment]
Pool share should not go to 0 from this slider. The pool share is based on total liquidity (my staked AND unstaked LP tokens).


https://user-images.githubusercontent.com/43685868/175761347-83ad14d2-4c34-4ee8-9116-bd206e89be27.mov

**Comment by BennyOptions** [comment]
This wallet has an open loan, but no staked LP tokens. The open loan is still eligible for Balance Token rewards, but it says "ineligible"

Screen Shot 2022-06-25 at 2 28 36 AM

**Comment by BennyOptions** [comment]
Look at the comparison between production (bottom) and this branch (top). I start the video by showing how quickly the "confirm transaction" message appears on my ledger. As soon as it appears after clicking the UI, I click "reject" on the ledger to show you the speed. It is very fast in production AND this branch when there is no transaction pending.

However, on **this branch** when a transaction is pending, the "confirm transaction" notification is extremely slow to appear on the ledger. The UI appears to be waiting for the notification to complete before sending the next transaction to the ledger. On current production, it is very fast even during a pending notification

**This Branch**
https://user-images.githubusercontent.com/43685868/175761569-358b7dc6-6c7f-46e6-8789-a712f51296c1.mov

**Production**
https://user-images.githubusercontent.com/43685868/175761699-ceff4756-4dfa-4bdc-8c52-ac01ae57ec87.mov

**Comment by parrot9design** [comment]
- Balance Tokens in the Rewards section is still showing as ineligible.

- When I reduce the browser window and the tooltip is pushed underneath, there's a certain width where there's not enough padding, so the tooltip overlaps the slider: 
Screen Shot 2022-06-25 at 6 28 42 PM

- When I try the same thing in the browser in responsive design mode, this doesn't happen, but between 600px-800px, the tooltip floats above, covering the top field. Let's always position it underneath:
Screen Shot 2022-06-25 at 6 34 52 PM

- We should also remove the decimal places, so instead of `10.00 bnUSD minimum`, it should say `10 bnUSD minimum`.

- I started with half my LP tokens staked before testing out the latest version. After I staked the full amount, the UI partially updated, showing these numbers before it updated again to reflect the correct amount:
Screen Shot 2022-06-25 at 6 37 00 PM

A similar thing happened when I then unstaked the full amount – it dropped to halfway before updating again to 0:
Screen Shot 2022-06-25 at 6 37 18 PM
Note that in both cases, the total amount of LP tokens should be 30.48.

**Comment by BennyOptions** [comment]
The slider should not appear if the user can't supply liquidity (0 base token and/or 0 quote token)


**Branch**
Screen Shot 2022-06-25 at 2 42 03 AM


**Production**
Screen Shot 2022-06-25 at 2 40 18 AM

**Comment by BennyOptions** [comment]
Also, for the tooltip, it should always say "10.00" for any token. I noticed in this comment it said "9.00 sICX"

https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-1166205536

**Comment by RiseBlock** [comment]
> This wallet has an open loan, but no staked LP tokens. The open loan is still eligible for Balance Token rewards, but it says "ineligible"
> 
> Screen Shot 2022-06-25 at 2 28 36 AM

This issue already happens with master branch, let's resolve it separately in another PR.

**Comment by BennyOptions** [comment]
There is also an issue now with supplying liquidity in small amounts. I am assuming it is leftover logic from tooltip/error handling for small amounts. Please remove all this logic.


https://user-images.githubusercontent.com/43685868/175781112-4fd62839-8152-4e87-a17a-d54b91c58454.mov

**Review by BennyOptions — APPROVED** [review]

**Pull request merged**
