### PR TITLE
fix: Ledger Integration/#333 Prevent users from interacting with UI

### PR DESCRIPTION
**Pull request by hieunguyenebox**

### CODE REVIEW

**Comment by hieunguyenebox** [comment]
@tuan-tl  @BennyOptions  please test again

**Comment by BennyOptions** [comment]
UX is good

**Review by tuan-tl — APPROVED** [review]

**Review by BennyOptions — COMMENTED** [review]
Found another small bug if the user refreshes the page when prompted to cancel a transaction. If this is difficult to fix, don't worry about it.


https://user-images.githubusercontent.com/43685868/126026562-2e7bba1d-b389-4d49-9638-48cfbfbc23b3.mp4

**Comment by hieunguyenebox** [comment]
@BennyOptions  fixed, please check again

**Comment by BennyOptions** [comment]
Good

**Review by BennyOptions — APPROVED** [review]
approve

**Pull request merged**
