### PR TITLE
Fix: change risk ratio bar color when passing "All Collateral Locked"

### PR DESCRIPTION
**Pull request by Chunn**
The result after fixed:
evidence

### CODE REVIEW

**Review by parrot9design — CHANGES_REQUESTED** [review]
This looks good, but we should make sure the space between `All collateral locked` and `Liquidated` is still done to scale: the bar shouldn't be completely filled unless you're about to be liquidated.

**Comment by Chunn** [comment]
> This looks good, but we should make sure the space between `All collateral locked` and `Liquidated` is still done to scale: the bar shouldn't be completely filled unless you're about to be liquidated.

@parrot9design I've fixed it based on your comment. Please check it again. Thank you!

image

**Review by parrot9design — APPROVED** [review]

**Comment by parrot9design** [comment]
This is behaving properly now, thanks @Chunn!

Screen Shot 2021-07-20 at 1 04 43 PM

**Comment by BennyOptions** [comment]
@WeiLi512 please review

**Pull request merged**
