### PR TITLE
Feat: create tooltip without arrow and border

### PR DESCRIPTION
**Pull request by Chunn**
**The result after fixed:**

image

image

### CODE REVIEW

**Review by parrot9design — CHANGES_REQUESTED** [review]
The tool tips should only be as wide as the text requires them to be, with 15px of padding on either side to make sure they're evenly balanced. 

To be specific, we have `padding: 10px 15px;` specified for both tool tips in the demo.

**Comment by Chunn** [comment]
@parrot9design  I've updated it.  Currently, the padding value default is 12px 16px. It seems it's OK. Please check it again. Thank you!
image

**Comment by parrot9design** [comment]
Hmm, I'm not sure why those are the default values, as we designed the interface with a 5px grid layout. It looks too rectangular with the current padding, so let's make it `10px 15px` (and set those values as the default). Thanks!

**Comment by Chunn** [comment]
> Hmm, I'm not sure why those are the default values, as we designed the interface with a 5px grid layout. It looks too rectangular with the current padding, so let's make it `10px 15px` (and set those values as the default). Thanks!

@parrot9design I've updated the tooltip based on your comment. Please check it again. Thank you!

**Review by parrot9design — APPROVED** [review]
This is great, thanks @Chunn!

**Review by WeiLi512 — APPROVED** [review]

**Pull request merged**
