### PR TITLE
fix: optimize trade page to reduce api calls

### PR DESCRIPTION
**Pull request by octocat512**

### CODE REVIEW

**Comment by BennyOptions** [comment]
Can u change this PR to main net when u get the chance?

**Comment by lijac** [comment]
> Can u change this PR to main net when u get the chance?

Yes, will do it after finishing WIP changes.

**Comment by BennyOptions** [comment]
Calculation of values of bnUSD and IUSDC in the IUSDC/bnUSD pool are incorrect. Also, the pool is backwards (possibly related, IUSDC must be 6 decimals while bnUSD is 18)

Screen Shot 2022-01-21 at 9 14 54 PM

Data refresh disrupts the app. It should only update prices

https://user-images.githubusercontent.com/43685868/150620952-0d4ac757-a5eb-4ac1-b50c-3c1b02011026.mov

**Comment by BennyOptions** [comment]
Two more videos showing issues with page glitching as price refreshes.


https://user-images.githubusercontent.com/43685868/150621688-111ce651-7402-4eff-9c54-0facea5fb054.mov


https://user-images.githubusercontent.com/43685868/150621689-5ffaf19f-afe4-408b-99dc-83bde2520346.mov

**Comment by BennyOptions** [comment]
I can't reproduce the issue, but the Trade page would not load.


https://user-images.githubusercontent.com/43685868/150622887-22cfb1b9-8336-4969-9a28-fe42292e58f3.mov

**Comment by BennyOptions** [comment]
After supplying liquidity, it shows "your supply" as empty

Screen Shot 2022-01-21 at 10 57 11 PM

**Comment by BennyOptions** [comment]
I am sure you are aware, but everything in the liquidity details section is backwards. I am sure it is also related to this comment (https://github.com/balancednetwork/balanced-network-interface/pull/846#issuecomment-1019018529).

Everything except bnUSD is reversed, including the number of coins. For example it is actually 43,925.54 BALN and 55,023.10 sICX

Screen Shot 2022-01-21 at 11 15 02 PM

**Comment by BennyOptions** [comment]
Notification is incorrect, should be

1,085 USDC and 1,087 bnUSD

Screen Shot 2022-01-21 at 11 40 31 PM

**Comment by BennyOptions** [comment]
One more withdraw issue when typing in the text box


https://user-images.githubusercontent.com/43685868/150626376-6b3818a7-7cd4-46da-b3da-745f15644ecb.mov

**Comment by BennyOptions** [comment]
Found another issue, this is big. The app breaks if u change "Swap" to IUSDC and "For" to "sICX"


https://user-images.githubusercontent.com/43685868/150626648-2b125520-5c41-4f07-be71-e28a31b9f2da.mov

**Pull request merged**
