### PR TITLE
feat: update v1 sdk version

### PR DESCRIPTION
**Pull request by shallcdn**
- [x] update v1 sdk version

#1050

### CODE REVIEW

**Comment by BennyOptions** [comment]
Hey @shallcdn please set this PR to main net so I can review. I added some guidelines to the readme for future reference.

https://github.com/balancednetwork/balanced-network-interface#contribution

**Comment by BennyOptions** [comment]
@hetfly can you take a quick look at this? This made some changes on how pairs are created in the DEX, want to make sure it doesn't impact transaction router at all. Probably separate, but just in case.

**Comment by hetfly** [comment]
@BennyOptions this has no impact on transaction router. To be sure I tested it out on multiple routes and they all matched the production ones.

**Review by hetfly — APPROVED** [review]

**Review by BennyOptions — APPROVED** [review]
LGTM

**Pull request merged**
