### PR TITLE
Fix: centering DropdownPopper

### PR DESCRIPTION
**Pull request by Chunn**
**The result after fixed:**

image
image
image

### CODE REVIEW

**Review by parrot9design — CHANGES_REQUESTED** [review]
It looks like this change reduced the spacing between the drop-down and the content above it. Let's push it down a bit.

**Current** | **[Demo](https://balanced.network/demo/trade/)**
----------- | ----------
Screen Shot 2021-07-30 at 2 00 35 PM | Screen Shot 2021-07-30 at 2 00 47 PM

While we're at it, can we have the hover effects (highlighted text + underline) for the pool remain active while the drop-down is visible? They currently only appear on mouseover.

----

The modals are centered within the section now, which is great. But, let's make them a bit wider – they should go outside of the content around them, rather than sit flush with it, as the slider is still partially visible, but if it's wider, like in the demo, you won't see anything:

**Current** | **[Demo](https://balanced.network/demo/trade/)**
----------- | ----------
Screen Shot 2021-08-02 at 5 30 47 PM | Screen Shot 2021-08-02 at 5 32 22 PM

**Comment by Chunn** [comment]
@parrot9design I've updated based on your comment.  Please check it. Thank you!

image
image

**Review by parrot9design — APPROVED** [review]
Much better, thanks @Chunn!

**Comment by WeiLi512** [comment]
I refactored the code. Please check the code and merge it into master if you are fine. @Chunn

**Comment by Chunn** [comment]
> I refactored the code. Please check the code and merge it into master if you are fine. @Chunn

@WeiLi512 It seems it's Ok. Currently, merging is blocked. Please help me merge it. Thank you!

**Review by WeiLi512 — APPROVED** [review]

**Pull request merged**
