### PR TITLE
Fix: update vote actions in the form [[method1, params1],...]

### PR DESCRIPTION
**Pull request by Chunn**

### CODE REVIEW

**Comment by Chunn** [comment]
> https://tracker.icon.community/transaction/0xeec4b8e31cdd1781543b7096e935835bf3968ea9d32a969e8babd3da3a316aee

@BennyOptions Thanks for sharing!

**Comment by BennyOptions** [comment]
Waiting for clarity from SC devs

**Comment by shallcdn** [comment]
LGTM

**Comment by BennyOptions** [comment]
@hetfly can u please review this PR? If it's good, reply here and tag @shallcdn

**Review by hetfly — APPROVED** [review]

**Comment by hetfly** [comment]
@shallcdn LGTM
couldn't test the proposal submit on berlin, tx can't go through, but the `actions` format is correct

**Pull request merged**
