### PR TITLE
Feat/add bsc & arb chain

### PR DESCRIPTION
**Pull request by 0xmilktea**

### CODE REVIEW

**Comment by parrot9design** [comment]
- [ ] Update the Supply & Bridge asset dropdowns to reflect the correct wallet balance.

- Supply = only show the balance of assets held in an ICON wallet
- Bridge = only show the balance of assets on the origination chain

---

- [ ] Change `Arbitrum One` > `Arbitrum`

---

- [ ] Can we round the bridge fee for BNB Chain to `0.0034 BNB`? The extra 0.0000116 amounts to $0.008, which isn't worth the space it occupies.

Screenshot 2024-06-06 at 4 44 30 PMScreenshot 2024-06-06 at 4 44 46 PM



---

- [ ] Can we update the wallet in the top right to include all EVM chains tied to the connected wallet? Or is this wrong for reasons I'm unaware of?
For example, when BNB Chain is the active chain in my EVM wallet, it says `BNB Chain wallet` in the top right and I only see the balance of assets on BNB Chain in the wallet dropdown. Yet the Swap panel simultaneously shows the balance & address of assets on Avalanche and Arbitrum, so it would be helpful to turn the top-right wallet dropdown into a `Multi-chain wallet` that lists the balances for each supported EVM chain. 
Screenshot 2024-06-06 at 12 21 36 PM

Thorswap allows you to see the wallet balance for multiple EVM chains, but you have to add each one explicitly.
Screenshot 2024-06-06 at 4 38 45 PM

---

- [ ] Change `Switch Network` > `Switch to {blockchain}`.
Screenshot 2024-06-06 at 3 48 03 PM > Screenshot 2024-06-06 at 5 27 02 PM


---

- [ ] Increase the decimal precision for some of the newer assets
Screenshot 2024-05-30 at 3 33 18 PMScreenshot 2024-06-06 at 3 18 51 PM
Screenshot 2024-06-06 at 4 54 28 PM

---

- [ ] Once a cross-chain swap or transfer is underway, can we update the `Cancel` button in the confirmation modal to say `Close` instead? There's no way to cancel the transaction once it gets to this point, so I don't want to give people the wrong impression.
Screenshot 2024-06-06 at 5 32 20 PM

**Comment by hetfly** [comment]
- [ ]  When signing with Archway, app goes white screen

**Comment by FezBox** [comment]
Can confirm - after I connected my keplr wallet my screen went white 
image

**Comment by parrot9design** [comment]
For the sign-in modal:

- [ ] Order the options alphabetically (Archway at the top)
- [ ] Add a full stop and external link icon after `View disclaimer`
- [ ] Change `assets` to `crypto` in `Swap and transfer assets cross-chain.`
- [ ] Change `Ethereum ecosystem` to `Ethereum & EVM ecosystem`
- [ ] Increase the modal width when the screen size is 400-600px (it looks unnecessarily thin currently)
- [ ] Improve the search functionality for EVM chains (results aren't consistent):
https://github.com/balancednetwork/balanced-network-interface/assets/63842577/d2c5ec11-a804-496d-a058-a6ca4a218396
- [ ] Prevent the search field from being active by default on mobile (brings up the on-screen keyboard, which isn't a great experience)
- [ ] Make the active EVM chain more prominent:
Screenshot 2024-06-11 at 4 49 25 PM

---

- [ ] Improve the empty state for EVM wallets, if possible:

**Current** | **Ideal**
----------- | -----------
Screenshot 2024-06-11 at 9 30 11 AM | Screenshot 2024-06-11 at 5 05 11 PM

>No EVM-based wallet detected.
>
>Add a wallet like [Hana](), [MetaMask](), or [Raby]() to your browser, then try again.

---

Outstanding from my [previous comment](https://github.com/balancednetwork/balanced-network-interface/pull/1341#issuecomment-2151447932):
- [ ] Update the wallet in the top right to include the balance of all EVM chains tied to the connected wallet.
Apps like Uniswap, Rango Exchange, and Zerion automatically pull in your wallet balance for each EVM chain, even though it's technically only active on one chain at a time. If they can do it, we should be able to without much hassle, right?

**Comment by AntonAndell** [comment]
Hey,
Could we also add BTCB and WTBC linked to BTC on this PR?
BNB BTCB: 0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c
ARB WBTC: 0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f

ICON BTC: cx07b184a37f03c6ab681fcbd0b45aec6dc3eafbeb

**Comment by parrot9design** [comment]
## Sign-in modal

- [ ] Let's put ICON first, and order every other chain alphabetically underneath (I wanted to avoid bias, but it is helpful to highlight the only chain that's fully supported).
- [ ] Update the ETH logo to use the same version as the Trade and Stats pages (that's our bad, sorry).
The ETH logo in the app is actually off-centre, so it might be a good time to revisit which of ETH's many faces we use. What do you think is more recognisable, the current version or this one? https://cryptologos.cc/logos/versions/ethereum-eth-logo-colored.svg?v=032

- [ ] Keep the blockchain logos visible on the left, even at smaller sizes. Without them, it's hard to scan the list and makes the right side of the modal look bare.


- [ ] Add a `Close` option to the modal when the screen size is below 600px so that it's easier to close on mobile. (Swiping down will sometimes dismiss the modal, but most of the time it bounces back so it's hard to get out of.)
Screenshot 2024-06-12 at 5 03 48 PM Screenshot 2024-06-12 at 5 04 07 PM


---

## Other

- [ ] Add `margin-bottom: 0px;` to the `Transfer time` entry in the swap metadata so there's consistent spacing at the top & bottom of the container.
Screenshot 2024-06-12 at 3 01 45 PM

- [ ] Increase the decimal precision to avoid showing `0.00` for small amounts (4-6 decimals will be helpful for higher-value tokens):
Screenshot 2024-06-12 at 3 14 56 PM
Screenshot 2024-06-12 at 3 23 46 PM
Screenshot 2024-06-12 at 4 09 15 PM
Screenshot 2024-06-12 at 4 12 36 PM
Screenshot 2024-06-12 at 4 12 54 PM

- [ ] Make the Bridge tab default to transfer ETH from Arbitrum to ICON 
- [ ] Update the activity text in the signed-in state to `You have no pending cross-chain transactions.`
- [ ] Add a buffer to the 100% option for native gas tokens (e.g. BNB on BSC, ETH on Arbitrum). If you choose 100% when you try to swap & transfer those assets currently, it won't trigger the wallet to sign the transaction.

----
Let's tackle these issues, in addition to the outstanding comments left by [myself](https://github.com/balancednetwork/balanced-network-interface/pull/1341#issuecomment-2159811353) and [Anton](https://github.com/balancednetwork/balanced-network-interface/pull/1341#issuecomment-2160079407), then this PR should be ready to go. @swiftcc624 @0xmilktea If any of these items can't/won't be addressed before launch, please mention it here so I know where we stand.

**Comment by parrot9design** [comment]
Swap transactions between Arbitrum & BNB Chain keep getting rolled back, but the UI acts like they're still pending. Are we able to detect when this happens, and either clear them or update the Activity section to say `REVERTED` instead?

**Comment by hetfly** [comment]
>so it might be a good time to revisit which of ETH's many faces we use

I'd say the purple one with its own background, so it doesn't matter where it's shown.

>Add a Close option to the modal when the screen size is below 600px

Updated, but there is a device check rather then width check, so you might not see it, depending on where you test.

**Comment by FezBox** [comment]
just tried to test a transfer from avax from Avalanche to ICON 

when clicking the transfer button, nothing happens 
image

**Comment by parrot9design** [comment]
Ok, here's what we need to take care of before we launch (ignore everything above unless I've called it out specifically):

- [ ] Update the BTC token (see [Anton's comment](https://github.com/balancednetwork/balanced-network-interface/pull/1341#issuecomment-2160079407))
- [ ] When you don't have enough of the gas token to pay for a transaction (e.g. BNB on BSC, ETH on Arbitrum), nothing happens when you click Swap or Transfer in the confirmation modal. Let's add a buffer to the 100% option for native gas tokens to account for the bridge + network fees (much like the 2 ICX buffer we have in place for ICON), and update the confirmation modal so people know when/why they can't go any further:
   

   >Add {gas token} to your wallet to cover transaction fees.

- [ ] Make BNB Chain the default for BNB and BTCB in the Swap panel, and make Arbitrum (or the currently active EVM chain) the default for ETH. After you choose one of these three tokens from the asset list, it should open the blockchain selector to show that you have options, like it does for bnUSD, AVAX, and sARCH.
- [ ] Update the Swap and Transfer tabs to support the bnUSD & ETH wallet balance for all EVM chains connected to your wallet, not just the active one.
- [ ] Fix the `For` wallet balance on the Swap tab so that it appears when the address is known. It currently remains hidden until a wallet is connected to the origination chain:
  Screenshot 2024-06-14 at 9 56 00 AM Screenshot 2024-06-14 at 10 10 58 AM
- [ ] Fix the order of assets in the dropdown. They're supposed to be ordered by wallet value, but it seems pretty random.
   Screenshot 2024-06-14 at 9 54 36 AM
- [ ] Add support for ETH on BNB Chain in the main wallet:
   Screenshot 2024-06-14 at 10 56 23 AM

- [ ] If we can squeeze it into this release, let's also improve the empty state for EVM wallets:

**Current** | **Ideal**
----------- | -----------
Screenshot 2024-06-11 at 9 30 11 AM | Screenshot 2024-06-11 at 5 05 11 PM


---

As mentioned in Discord, the UI is taking a long time to register the state of transactions.
- A transaction that was rolled back still shows as pending in the UI 2 hours later.
- Some transactions are pending for a _long time_, and I don't know whether that's on the smart contracts or the frontend. Transactions that involve arb &/or bsc seem to be the worst, but xcallscan only seems to show the [arb<>icon side of the transaction](https://xcallscan.xyz/messages/5361) so I can't see if or what went wrong.
Screenshot 2024-06-14 at 11 41 59 AM

- The destination chain balance can take a while to update on the Swap tab after the transaction has been cleared from the activity section (I noticed this with ETH and bnUSD specifically). I made the same cross-chain swap twice because my balance was still 0 after the first swap was complete. Even after the second swap, my balance remained at 0 until some amount of clicking around and force refreshing (or time) finally triggered it to update. 

---

>[show 1 item per transaction in bridge activity](https://github.com/balancednetwork/balanced-network-interface/pull/1341/commits/1c43658d506250837731c3642de74d1b41f92303)

Thanks for this, @0xmilktea! We were planning to rework the design next week to accommodate the previous behaviour, but this keeps it simple.

**Comment by parrot9design** [comment]
- [ ] The For field doesn't show zero balances for connected wallets, even though they appear when you reverse the swap.
Screenshot 2024-06-17 at 10 04 34 AM Screenshot 2024-06-17 at 10 04 27 AM

---

- [ ] For transactions that are rolled back, let's update the message in the Activity section to `REVERTED` (answers the question of what happened to the funds), and update the `Remove` link to use sentence case rather than all-caps:

**Current** | **Preferred**
----------- | -------------
Screenshot 2024-06-17 at 10 23 57 AM | Screenshot 2024-06-17 at 10 24 25 AM

---

- [ ] Once a transfer is in progress, the `Cancel` button should change to `Close` (because you can no longer cancel the transaction). The Swap confirmation modal has been updated to account for this, but the Transfer modal was missed.
Screenshot 2024-06-17 at 11 28 42 AM
Screenshot 2024-06-17 at 11 30 46 AM

---

- [ ] We still need to update the BTC token

**Comment by parrot9design** [comment]
- [ ] The percentage options don't work when you try to swap BNB on BNB Chain:

https://github.com/balancednetwork/balanced-network-interface/assets/63842577/855288f9-4d21-49eb-8570-96a15e550baf

**Comment by parrot9design** [comment]
When I try to swap or transfer ETH on BNB Chain, clicking Transfer in the confirmation modal doesn't trigger the wallet.
I'm not sure what the gas requirement is for this transaction, but my balance is `0.03438 BNB` and I have no issue when I swap/transfer bnUSD or BNB from BNB Chain.

**Comment by FezBox** [comment]
just tried to bridge eth from arbi to bsc and it has been pending for 7 minutes now - noticed this transaction has not shown up on xcallscan yet either 
image

**Comment by parrot9design** [comment]
My BSC <> ARB transactions are also stuck in a pending state (one for almost an hour now). I think it's related to ETH, though, as my last bnUSD transfer from ARB > BSC was done in 20 seconds.

---

- [ ] The risk bar on the Home page is a bit wonky compared to the live app. I'm not sure what was introduced that would affect this, but can we fix it up to avoid shipping any regressions?
Screenshot 2024-06-18 at 11 50 58 AM

**Comment by 0xmilktea** [comment]
merge executeTransfer and executeSwap core logic into one internal function in archway and evm.

**Comment by parrot9design** [comment]
Still a few decimal-related issues to take care of:

- BNB on ICON
- ETH on BNB Chain
- INJ on ICON

Screenshot 2024-06-19 at 9 58 38 AM Screenshot 2024-06-19 at 10 25 44 AM
Screenshot 2024-06-19 at 10 00 18 AMScreenshot 2024-06-19 at 10 15 29 AM

**Pull request merged**
