### PR TITLE
Add bnUSD savings UI

### PR DESCRIPTION
**Pull request by hetfly**

### CODE REVIEW

**Comment by parrot9design** [comment]
This tooltip should include the amount of bBALN you need for max rewards (to make the 58% make sense):

Lock up BALN to hold bBALN, which

If you have a loan/liquidity position, let’s make the final line say:
>You have **{amount}** bBALN. You need **{amount}** bBALN for 100% earning power.

Edit: The full message did appear, but only after I took out a loan. Let's still update it to the sentence above as the current version also has a grammatical error. 😊

---

The earnings should adjust as you move the slider. If it's just because I'm testing with small amounts, let’s make it show weekly earnings instead.
Confirm

---

When I sign out, the Earning Power section holds onto my BALN info until I refresh the page:
Screenshot 2024-02-21 at 4 57 08 PM

---

`Potential` should have an ellipsis after it:
Balanced incentives

I also only have one position here, so `positions require` should be `position requires`.

---

The first letter of each label should be capitalised here:
Loan interest
Let’s also show `0%` for the interest rate until it’s set to 2%, and make `Weekly interest` the default.

---
### Network fees tooltip

When you’ve locked up BALN and hover over the Earning Power tooltip in the read-only state, the Network Fee tooltip should lead with `You receive…` (`You’ll` is only for the adjustable state because the amount hasn’t been committed yet). 

BALN incentives for loans and

I came across this version when I unlocked early to test the initial states. It doesn’t update while you adjust your position, only after you commit it.
Lock up BALN

Also got this one, although it fixes itself as soon as you move the slider:
Network fees ®

The inconsistency I introduced with the contextual network fee tooltips is killing me. It’s quite jarring to see a different message depending on where you hover.
After you sign in and lock up BALN, let’s show the same message regardless of whether you hover over `Earning power` or `Network fees`:
Of the $3,403 Balanced distributed over

>You receive <strong>{amount}% </strong>of the fees shared with bBALN holders.<br><br>Of the <strong>${amount}</strong> Balanced distributed over the last 30 days, your share would have earned <strong> ${amount}</strong>.

---

Is it possible to hide this message until the interest is above 0%?
Borrow Balanced Dollars

---

I've adjusted the onboarding messages to feel more consistent with the existing UI:
Screenshot 2024-02-21 at 4 45 26 PM

### Top section

**bnUSD savings**
- Replace `p.a.` with `APR`

If signed out or signed in with no bnUSD:
>Buy or borrow bnUSD, then deposit it here to earn rewards.

If they have bnUSD:
>Deposit bnUSD to earn rewards, and withdraw when you need it.

If they're not signed in on ICON:
>Sign in on ICON, then deposit bnUSD to earn rewards.

**Earning power**
If signed out or signed in with no BALN:
>Earn or buy BALN, then lock it up here to boost your rewards.

If they have BALN:
>Lock up BALN to boost the amount you earn from rewards.

If they're not signed in on ICON:
>Sign in on ICON, then lock up BALN to boost your rewards.


### Bottom section
**bnUSD savings**
>To earn interest and other incentives, deposit bnUSD into your savings.

**Balanced incentives**
>To earn BALN, take out a loan or supply liquidity on the Trade page.

**Network fees**
>To earn fees from Balanced transactions, lock up BALN.

I'm also thinking we hide the interest rates from the bottom panel, as it contrasts with `Earning power` in a way that could be confusing, and there's not enough space to specify APR for each of them.

---

 Should we allow people to deposit bnUSD from other blockchains, now or in the future? Or do we want to limit xCall functionality to the Trade page?

**Comment by parrot9design** [comment]
Mobile is looking pretty good! Just a couple comments:

Might need to push this tooltip up a bit higher so it’s not in the way on mobile, even if that means giving it a taller triangle.
Rewards

--

The Balanced incentives tooltip doesn’t appear on mobile, I presume due to the space constraints?
bnUSD savings
Let’s make it so when you’re in the edit state or tap the icon next to earning power, only the Earning power message appears. We should also add a tooltip icon next to Balanced incentives so people can still view the impact to their rewards.

**Comment by hetfly** [comment]
@parrot9design Thanks for the thorough feedback!

Added fixes from the first comment, except for the onboarding messages for both savings and earning power for signed in user who has bnUSD / BALN with no locked amount. In this case there are the sliders already with buttons prompting to deposit / lock. Am I missing something?

**Comment by parrot9design** [comment]
>Added fixes from the first comment, except for the onboarding messages for both savings and earning power for signed in user who has bnUSD / BALN with no locked amount. In this case there are the sliders already with buttons prompting to deposit / lock. Am I missing something?

Nope, I think I was. 😅 All looks good on that front!

---
I know this number is still just a placeholder, but will it be based on rewards earned or claimed? Just want to make sure I've phrased it the right way.
Screenshot 2024-02-22 at 2 48 18 PM

---

The tooltips have been driving me fucking nuts, but I think I have it worked out this time around. 😅 To avoid content overload and tooltip hell, I've cut them down as much as possible. We can always adjust later if more clarification is needed.


<br>

**Before you sign in**

Earning power:
>Lock up BALN to hold bBALN, which earns network fees and boosts your BALN incentives for loans and liquidity pools.

Network fees:
>**$x** was distributed to bBALN holders in the last 30 days.

<br>

**When you're signed in, without bBALN**

The existing content is good:
Screenshot 2024-02-22 at 4 50 04 PM

No change needed for network fees, either.

<br>

**When you're in the editable state**
Screenshot 2024-02-22 at 3 29 24 PM

Earning power:
No change needed.

Network fees:
>You'll receive **x%** of the fees shared with bBALN holders, equivalent to **$x** over the last 30 days.

In this screenshot, I also increased the width of the `Balanced incentives` tooltip to 330px to avoid line breaks for the potential liquidity APR.

<br>

**Once you hold bBALN**

Earning power:
>Your earning power depends on your bBALN holdings and position size compared to everyone else's.
>
>You have **x bBALN**. You need **x bBALN** for 100% earning power.

(In essence, cut the `Lock up BALN...` message, keep the rest.)

Network fees:
>You receive **x%** of the fees shared with bBALN holders, equivalent to **$x** over the last 30 days.


----

Until you have bBALN or a loan/liquidity position, let's hide the % value beside earning power and `You have 0 bBALN.` in the tooltip:
Screenshot 2024-02-22 at 4 50 55 PM
(But make sure it still appears when you try to lock up BALN.)

---

When you address my mobile comments above, let's also push the rewards earned underneath the Rewards header:
IMG_6CA10B87534E-1

**Comment by hetfly** [comment]
@parrot9design added mobile and final tooltip feedback.

> The Balanced incentives tooltip doesn’t appear on mobile, I presume due to the space constraints?

Yeah

> I know this number is still just a placeholder, but will it be based on rewards earned or claimed?

It will probably be claimed + earned, so if you have claimed $15 in the last 30 days and you also have $5 unclaimed, that number will show $20 before and after you claim.

**Comment by parrot9design** [comment]
Ok, we had a bit of a discussion internally as we weren't happy with the initial state. Because there are 5 different sections, it makes Balanced's reward system seem too complex and risks alienating novice users who could previously use Balanced with confidence.

The solution we landed on is comparable to the [live Rewards section](https://app.balanced.network/), which shows only a single line of text until you qualify for rewards:

Screenshot 2024-02-23 at 11 39 31 AM

>To earn rewards: supply liquidity, deposit bnUSD into your savings, or lock up BALN.

Note: We could also add `borrow bnUSD,` to the start of this list (see the variation below), but I omitted it as the rewards are unremarkable so it shouldn't be anyone's first option, and I wanted to limit the word count. We do still mention it in the `Balanced incentives` onboarding message + the tooltip triggered by earning power, so I think that's enough.

<br>
To account for the network fees, let's add the info to the `Earning power` tooltip until you qualify for rewards and encounter the 3 different reward types:
light-tooltip

<br>
<br>
To make the copy more consistent across the Home page, let's also tweak these messages slightly:

**Loan section:**
>To borrow bnUSD, deposit collateral.

**Balanced incentives:**
>To earn BALN, borrow bnUSD or supply liquidity on the Trade page.
populated-light

**Comment by parrot9design** [comment]
Ok, this should be the last content change. Sorry to keep yo-yoing like this, but nailing down the right content style to use for this feature hasn't been easy, even though I've now come full circle. 😅

Rather than `bnUSD savings`, let's use `Savings rate` for the header (the former has been difficult to write about well in docs/marketing materials, and requires people to learn another phrase for the same thing).
Screenshot 2024-02-23 at 3 34 18 PM

We can then use `Deposit bnUSD` for the initial deposit button, which is more aligned with the `Lock up BALN` button.

It will require a small change to the reward message proposed in my previous comment:
>To earn rewards: supply liquidity, deposit bnUSD into the savings rate, or lock up BALN. 

And the reward category should also be called `Savings rate`.

**Comment by parrot9design** [comment]
Not sure what's up with the Loan section? It's taking quite a while to update here:

https://github.com/balancednetwork/balanced-network-interface/assets/63842577/a4ef58cf-3f7b-4507-8652-d136d81d3a4e

It could be related to the wallet I was testing with (`hx641c308dd736ff447ce27dc150af8188204819e3`), as I'm also having trouble doing anything related to collateral & loans (here or in the live app). This error always appears in Hana:

Screenshot 2024-02-26 at 11 44 09 AM

----

For numbers above 100, let's hide the decimals and round up instead:
IMG_FDF1BA3EA261-1

Also worth adding the bold+white style to the amount of bBALN needed to earn maximum rewards, as that's the target they need to hit.

---

Let's update the header for the savings rate reward modal:
Screenshot 2024-02-26 at 12 05 14 PM
>Claim Savings Rate rewards?

And for the banner messages:
>Claiming Savings Rate rewards...

>Claimed Savings Rate rewards

>Couldn't claim Savings Rate rewards.

---

Let's also make sure to remove the `Earned $x in the past month` message if the endpoint isn't ready yet.

---
Other than that, this is looking pretty solid. Nicely done, @hetfly! 💪 🔥

**Pull request merged**
